var objective_topic=["Three Phase : Objective Question"];
var subjective_topic=["Three Phase : Subjective Question"];

var objective_question=[
    [
		"1. WAG9H locos are based on______",
     "2. WAG9HI locos are based on ______",
     "3. Axle arrangement of WAP5 locos are______ type",
     "4. Axle arrangement of WAP7 locos are______ type",
     "5. Axle arrangement of WAG9 locos are______ type",
     "6. What is the OHE Voltage range of WAG9 loco?",
     "7. What is the gear ratio of WAG9 loco?",
     "8. What is the maximum speed limit of WAG9 loco?",
     "9. WAG9 loco can with stand frequency from______ to______ Hz",
     "10. Power of Traction motor in WAP5 is ______",
     "11. Power of Traction motor in WAG9 is ______",
     "12. Maximum Tractive effort of WAG9 HA is ______ KN",
     "13. First loco built in CLW was named ______",
     "14. BPCS stands for ______",
     "15. What is the full form of GTO?",
     "16. Force applied by parking brakes is ______",
     "17. BZ-V-O-F Buzzer for ______",
     "18. In which wheel parking brake is applied in WAG9 loco?",
     "19. Coder life of WAG9 loco is ______",
     "20. Horse power of WAP-5 loco is ______",
     "21. Horse power of WAG9 is ______",
     "22. Maximum permissible speed of WAP5 loco is ______",
     "23. Maximum permissible speed of WAP7 loco is ______",
     "24. Maximum speed of WAG9 loco is ______",
     "25. No of MR in WAP5 loco is ______",
     "26. Auxiliary reservoir capacity in WAG9 is ______",
     "27. MR reservoir capacity in WAG9 loco is ______",
     "28. Power supply in Traction motor of WAG9 loco is ______",
     "29. Now hotel load is available on ______ locos",
     "30. ALG stands for ______",
     "31. PCLH is ______",
     "32. FLG stands for ______",
     "33. SLG stands for ______",
     "34. What is the braking effort of WAG9 loco?",
     "35. What is the weight of WAG9 loco?",
     "36. How many Power Converters are there in WAG9 loco?",
     "37. Type of electrical braking used in WAG9 loco is ______",
     "38. In which locomotive brakes is applied on disc?",
     "39. BPFA stands for ______",
     "40. The primary voltage transformer reduces the catenary voltage, approximately 25 KV to ______ voltsAC.",
     "41. Potential transformer gives feed to ______",
     "42. Rating of PT Fuse is______",
     "43. Type of surge arrester case in 3 Phase loco is______",
     "44. Type of transformer used in 3 Phase loco is______",
     "45. Resistance of harmonic filter provided at ______",
     "46. What is the maximum output voltage of SR?",
     "47. What is the outputVariable frequencyof SRwhile in traction mode?",
     "48. Line convertor (NSR) convert ______ in traction mode.",
     "49. Line convertor (NSR) convert ______ in Braking mode.",
     "50. Input voltage of SR1/SR2 is ______",
     "51. DC link maximum voltage of SR1 is ______",
     "52. In 3 phase Loco Auxiliary motors are ______ motor ______",
     "53. Auxiliary Converters input voltage is1000 AC and output voltage is ______",
     "54. Auxiliary Converter-1 gives feed the auxiliary motors ______",
     "55. Auxiliary Converter-2 gives feed the auxiliary motors ______",
     "56. Auxiliary Converter-3 gives feed to auxiliaries ______",
     "57. The MCB for auxiliary converter-1 is ______",
     "58. The MCB for auxiliary converter-2 is ______",
     "59. The MCB for auxiliary converter-3 is ______",
     "60. Auxiliary converter-1 belongs to sub system no.______",
     "61. Auxiliary converter-2 belongs to sub system no.______",
     "62. Auxiliary converter-3 belongs to sub system no.______",
     "63. MCBs of OCB-1 and OCB-2 are ______",
     "64. MCBs of TMB-1 and TMB-2 are ______",
     "65. MCB’s of Transformer oil pump-1 & 2 are ______",
     "66. MCB’s of traction converter oil pump-1 & 2 are ______",
     "67. MCB’s of main compressors are ______",
     "68. MCBs for Scavenge blower-1 & 2 of OCB & TMB are ______",
     "69. MCB for Input of BA charger is ______",
     "70. MCB for Machine Room blower1 & 2 are ______",
     "71. MCB’s for Scavenge blower-1 & 2 of Machine room Blower are ______",
     "72. MCB for Cab heater ______",
     "73. MCB for Cab ventilation blower ______",
     "74. MCB for Crew fan ______",
     "75. MCB for Cab AC ______",
     "76. BUR-I can be isolated by the MCB ______ located in ______ panel.",
     "77. Which type of battery is used in WAG 9 loco?",
     "78. What is the capacity of WAG 9 loco battery?",
     "79. How many Numbers of batteries are there in WAG9 loco?",
     "80. Main switch for battery is ______",
     "81. For control circuit supply 1 MCB no. ______ is provided in SB2 in WAG9 loco.",
     "82. F1001P1 fault code refers to ______ .",
     "83. If brake electronics fail message appears on DDS the MCB to be cheeked ______ .",
     "84. The brake system refers to subsystem –",
     "85. The parking brake gauge shows above 3.8 Kg/cm2 on pressure gauge it means ______",
     "86. When parking brake pressure gauge shows 0 Kg/cm2 it means______",
     "87. In knorr CCB Loco vigilance penalty brake resetting time is ______ seconds.",
     "88. In E-70 brake system vigilance penalty brake resetting time ______ seconds.",
     "89. Parking brake can be released by pressing ______ switch",
     "90. During regenerative braking maximum braking effort available is ______ KN.",
     "91. If RB fail due to no tension, automatically braking effort activated by ______",
     "92. In 3phase loco BP pressure charged by ______ valve",
     "93. In 3 phase loco, By SA -9 loco brakes are applied through ______ valve",
     "94. In WAG-9 Loco VCD can be isolated by the switch ______ in ______Panel .",
     "95. If Loco brake is not applied ______ should be checked.",
     "96. If the Pneumatic Panel is not activated ______ key to be cheeked.",
     "97. No. of Main reservoirs provided in WAG-9 Loco ______",
     "98. MR pressure required to operate Reverser in WAG-9 Loco is ______",
     "99. Capacity of MCP in WAG-9 is ______",
     "100. MCB of Baby Compressor is ______",
     "101. MCB 48.1 is provided in ______",
     "102. The parking brake cannot be activated if the speed of the locomotive exceeds ______ Km/h.",
     "103. Position of cock no 47 in trailing loco in MU should be ______",
     "104. Position of cock no 74 in trailing loco in MU should be ______",
     "105. During Trail dead operation ______ are should in closed position.",
     "106. When A-9 is at full application position, B.C pressure will be ______ Kg/cm2",
     "107. Positions of A-9 in E-70 Brake System in 3 ɸ loco are ______.",
     "108. Positions of A-9 in Knorr CCB Loco are ______.",
     "109. Machine room control cubicles are ______",
     "110. Auxiliary Control cubicles are ______",
     "111. Auxiliary Transformer for 1phase is located in ______",
     "112. CEL1 is provided in –",
     "113. CEL2 is provided in ______",
     "114. HB2 provided in –",
     "115. SB2 provided in ______",
     "116. Train bus connecting Box is provided in ______",
     "117. OCR-78 is provided in ______",
     "118. Switch 152 for failure mode operation is provided in ______",
     "119. Switch 154 for Bogie isolation is provided in ______",
     "120. PT. Fuse is provided in ______",
     "121. TMB1 is provided in ______",
     "122. OCB is provided for cooling of ______ oil",
     "123. Pneumatic Panel is provided in ______",
     "124. Vigilance Control Unit is provided in ______",
     "125. Auxiliary Converter-3 is Provided in ______",
     "126. Auxiliary Converter-3 is provided inside ______",
     "127. Simulation Key 179 is located in ______",
     "128. Vigilance can be activate on pressing______",
     "129. Vigilancewill come in service at a speed of ______ KMPH.",
     "130. If LP press Vigilance foot switch for ______ Seconds, then penalty brake will apply.",
     "131. When LSVW Lamp glows, LP should acknowledge Vigilance within ______ Seconds.",
     "132. When Vigilance Penalty brake apply on loco, a fault code no.______ will appear on DDS.",
     "133. During Vigilance Penalty brake, BP will drop to______ in E70.",
     "134. After application of Vigilance penalty brake, LP will wait ______ seconds without operating any switch.",
     "135. To isolate Vigilance ______ switch to be operated.",
     "136. In case SPM defective ______ MCB to be operated.",
     "137. Emergency stop push button switch is provided in panel ______",
     "138. On pressing BPEMS a fault code No______ will appear in DDS.",
     "139. What will happen on pressing emergency stop push button switch ______",
     "140. When MR Pressure drops below 6.4 Kg/cm², which fault code will come on DDS______",
     "141. In case of failure of brake electronics, LP will check MCB ______",
     "142. In case of failure of brake electronics, a fault code No.______ will appearing in DDS.",
     "143. How many three phase 415 volt auxiliary circuit breakers are provided in HB1 ______",
     "144. How many single phase 415/110 Volt auxiliary circuit breakers are provided in HB1______",
     "145. How many three phase 415volt auxiliary Circuit breakers are provided in HBII______",
     "146. How many single phase 415/110 volt auxiliary Circuit breakers are provided in HB2______",
     "147. What Circuit breaker for pantograph VCB Control ______",
     "148. How many switches are provided in SB-1 Panel______",
     "149. 237.1 Switch where is Provided ______",
     "150. Failure mode operation switch is provided in ______",
     "151. Switch for bogie isolation is ______",
     "152. Which switch to be operate while VCD Multifunction______",
     "153. What is the name of the switch 160 ______",
     "154. The fire detection unit is provided in ______",
     "155. What is the full from of OCR-78______",
     "156. OCR-78 Provided in ______",
     "157. What is the normal position of switch 152______",
     "158. What is the normal position of switch 154 ______",
     "159. Which switch to be operated whenever speed can not to exceed beyond 15KMPH______",
     "160. MCB 110,112.1 where are provided in ______",
     "161. Which switch are provided for output BA Charger ______",
     "162. MCB for control circuit in 3 phase loco is______",
     "163. Switch 154 has ______ positions",
     "164. The circuit breaker provided for vigilance control in SB-2 panel is ______",
     "165. MCB No.212 is provided in ______",
     "166. MCB for central control electronics-1 is ______",
     "167. When cab fan is not working, MCB to be cheeked______",
     "168. Sub system for cab-I is ______",
     "169. During PTDC, MCB to be opened ______",
     "170. During PTDC operation PER-COS to be kept in ______ position",
     "171. In case of vigilance penalty brake initiated, wait for ______ seconds after bring back throttle to ‘O’ in E70.",
     "172. After putting auto brake handle to “Release” position for few seconds, BP would be charged to ______kg/cm²",
     "173. For recovery of “Penalty Service Brake”, auto brake handles to be kept in ______ position",
     "174. To overcharge BP to 5.5 kg/cm², auto brake handles to be kept in ‘Release’ position for minimum ______ seconds.",
     "175. For recovery of “Vigilance penalty brake”, A9 handle to be kept in______ position,",
     "176. During PTDC operation following MCB to be ensured in ‘ON’ position.",
     "177. Traction bogie-1 can be isolated by putting switch ______ on ______Position.",
     "178. Traction bogie-1 can be isolated by tripping MCB ______",
     "179. If throttle fails then the train can be worked by putting switch ______ on ______.",
     "180. If speed does not exceed 15KMPH, then ______ switch to be checked.",
     "181. When CE temperature exceeds 70°C then lamp ______ will glow.",
     "182. In MU operation ______ cocks of trailing loco should be closed.",
     "183. In non- driving cab position A9 is ______position in E70.",
     "184. During trail dead operation position of cock 47 should be ______ position",
     "185. During towed dead operation position of cock 47 should be ______ position",
     "186. To activate banking mode ‘ZBAN’ switch to beclosed in VCB______ condition.",
     "187. Constant speed control can be activated after reaching the speed of ______",
     "188. BPCS must not be pressed for more than time Period of ______seconds.",
     "189. CSC will be deactivated when ______ amount of pressure enters in brake cylinder.",
     "190. CSC can be deactivated by dropping BP to ______ through A9.",
     "191. In Knoor CCB Loco ______ to be adopted to clear block Section during failure of brake electronics.",
     "192. In case of brake electronics failed ______ fault will be displayed.",
     "193. TE/BE will not be possible if MR pressure drops below______ Kg/cm2",
     "194. In knoor CCB loco vigilance reset time is ______Seconds.",
     "195. What is the periodicity of POH in WAG9 loco?",
     "196. What is the periodicity of IOH in WAG9 loco?",
     "197. What is the periodicity of TOH in WAG9 loco?",
     "198. What is the periodicity TI WAG9 loco?",
     "199. What is the time duration of TI in WAG9 loco?",
     "200. What is the time duration of IA in WAG9 loco?",
     "201. What is the time duration of IB in WAG9 loco?",
     "202. What is the time duration of IC in WAG9 loco?",
     "203. What is the time duration of TOH in WAG9 loco?",
     "204. What is the time duration of IOH in WAG9 loco?",
     "205. What is the time duration of POH in WAG9 loco?"
    ]
];

var objectiveoptions=[
    [
		["a) GTO ","b) IGBT ","c) None of this"],
		["a) GTO ","b) IGBT ","c) None of this"],
		["a) Bo-Bo type ","b) Co-Co type ","c) None of these"],
		["a) Bo-Bo type ","b) Co-Co type ","c) Bo-Bo-Bo"],
		["a) Bo-Bo type ","b) Co-Co type ","c) Bo-Bo-Bo"],
		["a) 17.5 KV -30 KV ","b) 16.5- 28.5 KV ","c) 23.5- 30.0 KV"],
		["a) 1:3.65 ","b) 1:5.133 ","c) 1:3.6"],
		["a) 110 KMPH ","b) 105 KMPH ","c) 100 KMPH"],
		["a) 45-55 ","b) 50-55 ","c) 55-60"],
		["a) 1155 HP ","b) 1156 HP ","c) 1563 HP"],
		["a) 1563 HP ","b) 1156 HP ","c) 1155 HP"],
		["a) 458 ","b) 450 ","c) 520"],
		["a) NAV YUG ","b) NAV DISHA ","c) NAV JOTI"],
		["a) Push button switch for cooling system ","b) Push button switch for Control system ","c) Push button switch for Constant speed control"],
		["a) Gate Turn ON ","b) Gate Turn over ","c) Gate Turn Off"],
		["a) 37 KN ","b) 317 KN ","c) 307 KN"],
		["a) vigilance, over speed and fire ","b) vigilance, over voltage in OHE and fire ","c) vigilance, over speed and fault in loco"],
		["a) Wheel No. 2,6,7& 11 ","b) Wheel No.2,6,8 & 11 ","c) Wheel No.2,4,7 & 11"],
		["a) 25 years ","b) 35 years ","c) 45 years"],
		["a) 6000 HP ","b) 6120 HP ","c) 5440 HP"],
		["a) 6120 HP ","b) 5440 HP ","c) 6000 HP"],
		["a) 100 Kmph ","b) 130 Kmph ","c) 160 Kmph"],
		["a) 160 Kmph ","b) 130 Kmph ","c) 100 Kmph"],
		["a) 160 Kmph ","b) 130 Kmph ","c) 100 Kmph"],
		["a) 3 ","b) 2 ","c) 1"],
		["a) 260 litre ","b) 240 litre ","c) 140 litre"],
		["a) 450 litre ","b) 350 litre ","c) 250 litre"],
		["a) 2100V ","b) 2180V ","c) 1180V"],
		["a) WAG9 ","b) WAP5 ","c) WAP7"],
		["a) Drive control unit ","b) Drive converter ","c) Line converter"],
		["a) Socket for desk lamp ","b) Socket for hand lamp ","c) Socket for driving cab"],
		["a) Vehicle control unit ","b) Drive control unit ","c) Line converter"],
		["a) Drive Converter ","b) Drive Control Unit ","c) Converter Control Unit"],
		["a) 460 KN ","b) 260 KN ","c) 160 KN"],
		["a) 123 T ","b) 120 T ","c) 132 T"],
		["a) 3 nos ","b) 2 nos ","c) 4nos"],
		["a) Regenerative ","b) Rheostatic ","c) None of this"],
		["a) WAP5 ","b) WAG9 ","c) WAP7"],
		["a) Push button for Failure activation ","b) Push button for Fire Alarm acknowledgement ","c) Push-button for Acknowledgement all fault Messages"],
		["a) 220 ","b) 110 ","c) 48"],
		["A) Main Converter electronic ","b) Catenary voltmeters ","c) Both"],
		["A) 1A ","b) 2A ","c) 6 A"],
		["A) Gapless ","b) Rod gap type ","c) Both are used"],
		["A) Auto ","b) step up ","c) Parallel induction"],
		["A) In M/C room ","b) Roof of the loco ","c) Inside the SR"],
		["A) 750 V ","b) 2180 V ","c) 440 V"],
		["A) 50 to 125 Hz ","b) 50 to 65 Hz ","c) From 65 to 132 Hz"],
		["A) AC to DC ","b) DC to AC ","c) Both"],
		["A) AC to DC ","b) DC to AC ","c) Both"],
		["A) 960V ","b) 1000V ","c) 1269V"],
		["A) 2800V ","b) 1000V ","c) 2180V"],
		["a) DC motor ","b) Squirrel cage induction motor ","c) DC series motor"],
		["a) 415V AC 3 ɸ ","b) 415V AC single ɸ ","c) 380V AC 3 ɸ"],
		["a) OCB-1/2 ","b) TMB-1/2 ","c) MCP-1/2"],
		["a) OCB-1/2 ","b) TMB-1/2 ","c) MCP-1/2"],
		["a) OCB-1/2 ","b) TMB-1/2 ","c) MCP-1/2& CHBA"],
		["a) 127.22/1 ","b) 127.22/2 ","c) 127.22/3"],
		["a) 127.22/2 ","b) 127.22/1 ","c) 127.22/3"],
		["a) 127.22/1 ","b) 127.22/3 ","c) 127.22/2"],
		["a) SS-05 ","b) SS-06 ","c) SS-07"],
		["a) SS-05 ","b) SS-06 ","c) SS-07"],
		["a) SS-06 ","b) SS-07 ","c) SS-08"],
		["a) 53.1/1 & 53.1/2 ","b) 59.1/1 & 59.1/2 ","c) 55.1/1 & 55.1/2"],
		["a) 53.1/1 & 53.1/2 ","b) 59.1/1 & 59.1/2 ","c) 47.1/1 & 47.1/2"],
		["a) 55.1/1 & 55.1/2 ","b) 62.1/1 & 62.1/2 ","c) 63.1/1 & 63.1/2"],
		["a) 62.1/1 & 62.1/2 ","b) 63.1/1 & 63.1/2 ","c) 53.1/1 & 53.1/2"],
		["a) 62.1/1 & 62.1/2 ","b) 47.1/1& 47.1/2 ","c) 53.1/1 & 53.1/2"],
		["a) 54.1/1 & 54.1/2 ","b) 55.1/1 & 55.1/2 ","c) 56.1/1 & 56.1/2"],
		["a) MCB-100 ","b) MCB-110 ","c) MCB-112"],
		["a) 54.1/1 & 54.1/2 ","b) 55.1/1 & 55.1/2 ","c) 56.1/1 & 56.1/2"],
		["a) 55.1/1 & 55.1/2 ","b) 56.1/1 & 56.1/2 ","c) 57.1/1 & 57.1/2"],
		["a) 69.62 ","b) 54.1/1 ","c) 56.1/2"],
		["a) 69.41 ","b) 69.51 ","c) 69.61"],
		["a) 69.71 ","b) 69.62 ","c) 69.61"],
		["a) 63.1 ","b) 64.1 ","c) 65.1"],
		["a) 127.22/1 in HB-1 ","b) 127.22/1 in SB-1 ","c) 127.22/3 in SB-2"],
		["a) Lead acid ","b) NiCd ","c) Lithium Ion."],
		["a) 120 Ah ","b)150 Ah ","c) 199 Ah"],
		["a) 10 ","b)12 ","c) 26"],
		["a) 112 ","b)110 ","c) 100"],
		["a) 112.1 ","b)110.1 ","c) 100.1"],
		["a) Brake electronics fail ","b) Control electronics ","c) Central electronics"],
		["a) 127.15 ","b) 127.7 ","c) 127.12"],
		["a) SS-08 ","b) SS-9 ","c) SS-10"],
		["a) Parking brake is released condition ","b) Parking brake is applied condition ","c) Loco brake in applied condition"],
		["a) Parking brake is released condition ","b) Parking brake is applied condition ","c) Loco brake in applied condition"],
		["a) 32 ","b) 90 ","c) 120"],
		["a) 32 ","b) 90 ","c) 120"],
		["a) BPPB ","b) Solonide-30 ","c) Both"],
		["a) 160 ","b) 260 ","c) 300."],
		["a) Solonide valve ","b) Anti compound valve ","c) Blending Valve"],
		["a) E-70 ","b) 57 valve ","c) 58 valve"],
		["a) E-70 ","b) 58 ","c) 57"],
		["a) 237.1, SB-1 ","b) 237.1, SB-2 ","c) 136, Pneumatic panel"],
		["a) SR-1cock ","b) Cock no -94 ","c) SR-2 cock"],
		["a) IG-38 ","b) 179 ","c) BL"],
		["a) 4 Nos. ","b) 3 Nos ","c) 2 Nos"],
		["a) 6.4 Kg/cm2 ","b) 8 kg/cm2 ","c) 6kg/cm2"],
		["a) 1500 LPM ","b) 1700 LPM ","c) 2000LPM"],
		["a) 48.1 ","b) 47.1/1 ","c) 48.1/1"],
		["a) HB-2 Panel ","b) SB-1 Panel ","c) SB-2 Panel"],
		["a) 3 ","b) 5 ","c) 1.5"],
		["a) Closed ","b) Open ","c) Neutral"],
		["a) Closed ","b) Open ","c) Neutral"],
		["a) 70,136 & 74 ","b) 74,136 & 47 ","c) 70,74,136 & 47"],
		["a) 1.8 ","b) 2.5 ","c) 3.5"],
		["a) 4 ","b) 5 ","c) 6"],
		["a) 5 ","b) 6 ","c) 7"],
		["a) SB1 & SB2. ","b)HB1& HB2 ","c) Both"],
		["a) SB1 & SB2 ","b) HB1 & HB2 ","c)Both"],
		["a) HB1 ","b) HB2 ","c) SB1"],
		["a) HB2 ","b) SB1 ","c) HB2"],
		["a) HB2 ","b) HB1 ","c) SB2"],
		["a) Machine Room1 ","b) Machine Room2 ","c) Non of these."],
		["a) Machine Room1 ","b) Machine Room2 ","c) None of these."],
		["a) SB1 ","b) SB2 ","c) HB2"],
		["a) HB1 ","b) SB1 ","c) HB2"],
		["a) SB2 ","b) HB1 ","c) SB1"],
		["a) SB1 ","b) SB2 ","c) HB1"],
		["a) HB2 ","b) SB2 ","c) SB1"],
		["a) Machine Room1 ","b) Machine Room2 ","c) under frame"],
		["a) Only TFP ","b) Only SR ","c) TFP & SR"],
		["a) Machine Room1 ","b) Machine Room2 ","c) under frame"],
		["a) Cab-2 ","b) Machine Room1 ","c) Machine Room 2"],
		["a) Machine Room1 ","b) Machine Room2 ","c) None of these"],
		["a) BUR2 ","b) BUR1 ","c) HB-2"],
		["a) HB2 ","b) SB1 ","c) Pneumatic panel"],
		["a) BPCS ","b) BPVR ","c) Sander"],
		["a) 1 ","b) 1.5 ","c) 2"],
		["a) 60 ","b) more than 60 ","c) 32"],
		["a) 8 ","b) 10 ","c) 15"],
		["a) F1103P1 ","b) F1003P1 ","c) F0903P1"],
		["a) 0Kg/cm² ","b) 1 to 1.5 Kg/ cm² ","c)2.5 to 3 Kg/ cm²"],
		["a) 60 ","b) 120 ","c)180"],
		["a) 237.1 ","b) 160 ","c)154"],
		["a) 127.9/1 ","b) 127.9/2 ","c)127.92"],
		["a) A ","b) B ","c) C"],
		["a) F1008P2 ","b) F1008P1 ","c) F1108P1"],
		["a) BP will drop to ‘0’ ","b) DJ will trip ","c)Both."],
		["a) F1102P1 ","b)F1002P1 ","c) F0902P1"],
		["a) 127.7 ","b)127.15 ","c)127.1"],
		["a) F1001P1 ","b) F1001P2 ","c) F0901P1"],
		["a) 6 ","b) 5 ","c) 7"],
		["a) 4 ","b) 5 ","c) 6"],
		["a) 5 ","b) 6 ","c) 7"],
		["a) 2 ","b) 3 ","c) 4"],
		["a) 127.15 ","b) 127.12 ","c) 127.7"],
		["a) 2 ","b) 3 ","c) 4"],
		["a) HB-1 ","b) SB-1 ","c) SB-2"],
		["a) SB-1 ","b) SB-2 ","c) HB-2"],
		["a) 152 ","b) 160 ","c) 154"],
		["a) 237.0 ","b) 237.1 ","c) 127.12"],
		["a) Configuration ","b) Bogie isolation ","c) Failure mode operaation"],
		["a) HB-1 ","b) HB-2 ","c) SB-2"],
		["a) Over voltage Relay ","b) Over current Relay ","c) Minimum voltage Relay"],
		["a) SB-1 ","b) SB-2 ","c) HB-2"],
		["a) ‘1’ ","b) ‘O’ ","c) ‘2’"],
		["a) NORM ","b) I ","c) I, II"],
		["a) 152 ","b) 154 ","c) 160"],
		["a) SB-1 ","b) SB-2 ","c) HB-1"],
		["a) 110 ","b) 100 ","c) 112.1"],
		["a) 112 ","b) 112.1 ","c) 110"],
		["a) 2 ","b) 3 ","c) 4"],
		["a) 127.15 ","b) 127.7 ","c) 127.12"],
		["a) SB-1 ","b) SB-2 ","c) HB-1"],
		["a) 127.9/2 ","b) 127.1/1 ","c) 127.9/1"],
		["a) 69.62 ","b) 69.71 ","c) 69.31"],
		["a) SS 13 ","b) SS14 ","c) SS17"],
		["a) 127.7 ","b) 127.12 ","c) 127.15"],
		["a) Isolate ","b) Horizontal ","c) Vertical"],
		["a) 120 ","b) 160 ","c) 32"],
		["a) 5.4 ","b) 5.5 ","c) 5"],
		["a) Release ","b) Full service ","c) Emergency"],
		["a) 3 ","b) 4 ","c) 5"],
		["a) Release ","b) Full service ","c) Emergency"],
		["a) 127.15 ","b) 127.7 ","c) 127.12"],
		["a) 152, ‘0’ ","b) 154, I ","c) 154, ‘0’"],
		["a) 127.1/1 ","b) 53.1/1 ","c) 127.22/1"],
		["a) 152, ‘0’ ","b) 152, I ","c) 152 , OFF"],
		["a) 154 ","b)237.1 ","c) 160"],
		["a) LSFI, BPFA ","b)LSDJ, LSFI ","c) LSCE, BPFA"],
		["a) 70,47 ","b)136,70 ","c)136, 47"],
		["a) Neutral ","b) Release ","c) Run"],
		["a) Open ","b) Close ","c) Any"],
		["a) Open ","b) Close ","c) Any"],
		["a) Open ","b) Close ","c) Any Position"],
		["a) 1.5 KMPH ","b)15 KMPH ","c) 5 KMPH"],
		["a) 05 ","b)15 ","c) 60"],
		["a) 0.25Kg/cm² ","b) 0.65Kg/ cm² ","c) 1Kg/cm²"],
		["a) 1Kg/cm2 ","b) 0.65Kg/cm2 ","c) 0.25Kg/cm2"],
		["a) DCPT ","b) PTDC ","c) CCPT"],
		["a) P 1 ","b) P 2 ","c) Non of the above"],
		["a) 5.2 ","b) 6.4 ","c) 6.8"],
		["a) 60 ","b) 32 ","c) 120"],
		["a) 18 months + 15 days  ","b)12 years + 6 months or 24 lakh kms. whichever is earlier. ","c) 6 years + 3 months or 12 lakh kms whichever is earlier"],
		["a) 18 months + 15 days  ","b) 36 months + 1 month or 6 lakh for whichever is earlier ","c) 6 years + 6 months or 12 lakh kms.whichever is earlier."],
		["a) 24 months + 15 days  ","b) 36 months + 1 month or 6 lakh for whichever is earlier ","c) 18 months "],
		["a) 20 days ","b) Every trip ","c) 45 days"],
		["a) 2 hours ","b) 4 hours ","c) 6 hours"],
		["a) 2 hours ","b) 4 hours ","c) 6 hours"],
		["a) 2 hours ","b) 4 hours ","c) 6 hours"],
		["a) 2 hours ","b) 8 hours ","c) 6 hours"],
		["a) 6 working days ","b) 9 working days ","c) 24 working days"],
		["a) 6 working days ","b) 11 working days ","c) 24 working days"],
		["a) 6 working days ","b) 9 working days ","c) 28working days"]
	]
];

var objectiveAnswer=[
    [
		1,2,1,2,2,1,2,3,1,3,2,3,1,3,3,1,1,1,2,3,1,3,2,3,1,2,
		1,2,3,1,2,1,3,2,1,2,1,1,3,1,3,2,1,3,2,2,3,1,2,3,1,2,
		1,1,2,3,1,1,2,2,3,3,1,1,2,2,2,2,1,1,2,1,3,1,2,2,2,3,
		3,1,1,1,2,3,1,2,1,3,3,2,3,1,3,1,2,1,3,1,1,1,3,2,1,2,
		3,2,3,1,1,2,1,2,3,2,2,1,2,3,1,3,2,3,1,2,2,1,2,3,2,2,
		1,2,3,2,1,3,1,2,3,2,1,1,1,2,2,1,2,3,2,1,3,2,1,3,2,1,
		2,1,3,2,1,2,3,1,2,3,2,1,1,3,1,1,2,1,2,1,2,1,2,3,3,3,
		1,2,1,1,3,1,2,3,2,1,2,2,2,3,3,3,2,2,3,2,1,2,3
	]
];

var subjective_question=[
    [
		"Q1. What are the advantages of WAG 9 locomotive?",
		"Q2. What are the main mechanical parts of WAG 9 locomotive?",
		"Q3. Write the short note about potential transformer of WAG9 loco fitted on roof.",
		"Q4. Describe the traction power circuit of WAG9 loco.",
		"Q5. Write the name of different 3 phase, 415 voltauxiliary motors and their location and functions.",
		"Q6. Write about the load sharing of auxiliary convertor.",
		"Q7. Write the name of different single phase, 415/110 voltloads and their location and functions.",
		"Q8. How many types of brake system are there in WAG 9 locomotive?",
		"Q9. Write short note on A9 of WAG9 loco.",
		"Q10. Write short note on A9 of WAG9 loco.",
		"Q11. Write short note on Anti spin brake of WAG9 loco.",
		"Q12. Write short note on brakes through blending valve of WAG9 loco.",
		"Q13. Write short note on parking brake of WAG9 loco.",
		"Q14. When does emergency brake apply through brake electronics in WAG9 locomotive?",
		"Q15: How many number of sub systems are there in three phase loco and write their names?",
		"Q16: What do you mean &ldquo;status code&rdquo; and how you will read it?",
		"Q17. When is it required to switch OFF MCE &amp; write thetheprocedure ?",
		"Q18. How will loco pilot activate cooling mode?",
		"Q19. what general safety precautions are to be followed while working in WAG9 Loco?",
		"Q20. What are the different bogie clearances of WAG9 locomotive?",
		"Q21. What are the Limits for Wheel Set dimension variations and wheel wear of three phase electric locomotives?",
		"Q22. What is handling process of fibre Optic Connections to keep it safe?",
		"Q23. What is the procedure to ground the traction convertor?",
		"Q24. Write about the inspection schedule of WAG9 locomotive.",
		"Q25. Write about the</strong><strong>inspection of traction bar during IC inspection.",
		"Q26. Write about the inspection of bogie frame and brake gear of WAG9 loco in minor schedules.",
		"Q27. Write about the inspection of pantograph of WAG9 loco in minor schedules.",
		"Q28. Write about the inspection of main transformer of WAG9 loco in minor schedules.",
		"Q29. Write the inspection procedure of traction convertor of WAG9 loco in minor schedules.",
		"Q30. Write the inspection procedure of traction motor of WAG9 loco in minor schedules.",
		"Q31. Write the inspection procedure of </strong><strong>harmonic filter </strong><strong>of WAG9 loco in minor schedules.",
		"Q32. How to handle PCB of WAG 9 loco? What precautions are to be taken?",
		"Q33. Write the name of the VCU cards of WAG9 loco.",
		"Q34. Write the short note on Hotel load of 3 phase loco.",
		"Q35. What do you mean by Fault with priority 1 and Fault with priority 2 in WAG9 Loco?"
    ]
];

var subjective_answer=[
    [
		"<strong>Ans -</strong> The merits of 3-phase locomotives over D.C.-motor locomotives are summarized below.</p><p>1. The size of traction motor for the same output power is much less in case of a 3-phase induction motor compared to DC motor. Therefore, with the permissible axle load and available space in a bogie, realization of a much higher-powered loco motive is possible.</p><p>2.&nbsp; Maintenance cost of a 3-phase locomotive is less due to absence ofbrush-gear/ commutator in the traction motors and switchgears in the power circuit.</p><p>3.&nbsp; Induction motors are very robust. Consequently reliability of a 3-phase locomotive is higher.</p><p>4.&nbsp; The rated power of a D.C.-motored locomotive reduces beyond the field weakening range. In case of 3-phase loco motives, full power is available up to the maximum speed.</p><p>5. Overload capabilities in 3-phase locomotives are more Liberal.</p><p>6. Regeneration of power is available in 3-phase locomotives. Regenerative braking effort is available from the full speed till dead stop. Consequently, the overall efficiency of operation is higher.</p><p>7.&nbsp; Due to superior drop characteristics of speed Vs. torque and the fact that the motor speed is limited by the synchronous speed, a much improved adhesion is available in 3-phase locomotive and thus higherTractive efforts can be realized within permissible axle load limits.</p><p>8. 3-phase locomotive operates at near unity power factor throughout the speed range except at very low speeds.</p><p>9. Due to lesser weight of the traction motors, the un-sprung masses in 3-phase locomotive are low. This reduces track forces and consequently minimizes wear on rails and disturbance to track geometry.</p>",
		"<strong>Ans - </strong><br/>1. Sanding box&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2. Wheel flange lubrication nozzle3. Primary suspension damper 4. Secondary suspension yaw damper&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 5.Wheel flange lubrication reservoir&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6. Secondary suspension spring7. Safety chain `&nbsp;&nbsp; &nbsp;8.Secondary suspension vertical&nbsp; damper9.Horizontal damper&nbsp;&nbsp; 10. Wheel set guide11. Bogie frame 12.Sanding box13. Wheel set 14.Wheel15. Brake blocks 16. Brake lever17. Brake cylinder 18.Brake rod19. Primary suspension spring 20.Wheel flange21. Sanding pipe 22. Traction link23.Anti compounding valve</p>",
		"<strong>Ans - </strong><br/>The primary voltage transformer is situated on the converter roof hatch andattached to the pantograph via the roofline. The primary voltage transformerreduces the catenary voltage, approximately 25 kV, to 200 volts AC. A resistoris placed across the primary voltage transformer to provide a reference load.<br/>The output signal is used in three ways;<br/>1) Main converter electronics = 4 volt AC<br/>2) Catenary voltmeters on the driver&rsquo;s console = 10 volt DC<br/>3) Minimum voltage relay.<br/>When panto is raised this potential transformer fed to U meter and U metershows the OHE supply in drivers cab.<br/>As such we can have an idea of availability of OHE supply before closing DJand also idea of rising of panto. However our responsibility of seeing panto isnot finished, we have to check the condition of panto physically. </p>",
		"<strong>Ans - </strong><br/>Power from the overhead Catenary is directed to the main transformer, mounted on the locomotive under frame, via the pantograph. The traction circuit is split into two separate circuits after the main transformer.<br/>The traction converters can conduct current from the Catenary to the traction motors to provide propulsion, or can act as in the opposite manner conducting, and rectifying, current from the traction motors to the Catenary. This allows the converter to work in both traction and braking mode. During braking the traction motors act as generators feeding power back into the catenary. The traction converters then act to convert the three phases into single phase for the catenary.</p><p>The traction converters provide continuous and automatic control of both speed and torque of the traction motors according to the driver&rsquo;s demand. The converters are controlled by the converter control electronics, and thelocomotive central electronics.<br/>Three, 3-three phase asynchronous traction motors are connected in parallel to each traction converter.</p><p><strong>Traction Converter: (SR)</strong><br/>Traction converter converts single-phase 25 KV AC supply into 3 phase AC,with Variable Voltage (max 2180 V) and frequency (from 65 to 132 Hz) whiletraction mode and fed it to traction motor group -1.<br/>As such there are two traction converter i.e. Traction converter-1 for TM 1-2-3<br/>and Traction converter-2 for TM 4-5-6.( In case of WAP-5 , traction converter-1<br/>for TM 1-2 and Traction converter-2 for TM-3-4)<br/>While electrical braking the traction motor works as a generator and fedgenerated 3-phase supply to Traction converter. This converter now act inreverse manner i.e. it converts 3 phase AC supply into single phase AC supplyand fed it to Transformer. Further main transformer steps up this supply andfed back to OHE. In this way 3 phase loco works as a small powerhouse, whichgenerate supply and share the load by feeding it back to OHE.<br/>SR is cooled by two separate oil cooling unit.<br/>The traction converter has three main sub parts:<br/>1) Line Converter 2) Intermediate DC link and 3) Drive converter.<br/>One spy glass is provided on each SR to check the oil level.</p><p><strong>Line Converter :(NSR)- </strong><br/>The line converter converts the alternating current supplied from the main<br/>transformer into direct current (motoring) and forwards this direct current to the<br/>intermediate DC-Link. However, it is also able to convert direct current from the<br/>intermediate DC-Link into alternating current and to supply this alternating<br/>current in turn to the main transformer (braking). Both functions are activated<br/>by the traction converter control electronics.</p><p><strong>&nbsp;DC Link:</strong><br/>The intermediate DC-Link performs two main tasks. Firstly, it smoothes the<br/>direct current that flows through. Secondly, it also performs the storagefunction, thus covering the peak current demand of the line converter or of themotor. It works as an electrical buffer between ASR and NSR</p><p><strong>Drive Converter- (ASR):</strong><br/>The drive converter converts the direct current from the intermediate DC-Link<br/>into three-phase current for the drive motors (motoring). Conversely, it is also<br/>able to convert the three-phase current generated by the drive motors intodirect current for braking. The construction of the motor inverter valve set isidentical to that of the line converter. The complete assembly of line converterNo.1, DC link and drive converter No.1 is termed as &ldquo;TRACTIONCONVERTER NO.1&rdquo; which in turn converts 1-phase AC supply of maintransformer into 3-phase AC supply with variable voltage and frequency andfed to the 3-phase traction motor.</p><p><strong>Traction Motor:</strong><br/>There are total 6 traction motors provided in WAG-9 loco. TM 1-2-3are mounted in bogie-1 and fed from traction converter -1 whereas TM 4-5-6are mounted in bogie -2 and fed from traction converter -2. <br/>Traction motor is suspended on axle, by axle cap at one end and on link atanother end.<br/>To check the oil in gear case one spy glass is provided on gear case. To monitor the temperature &amp; speed, sensors are provided in the statorassembl</p>",
		"<strong>Ans - </strong><br/>Following 3 phases, 415-volt auxiliaries are provided on this loco, which are fed from Auxiliary converter no. 1, 2 and 3.</p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='187' valign='top'><br/><strong>Auxiliary</strong> </td><td width='174' valign='top'><p align='center'><strong>Location</strong></p></td><td width='331' valign='top'><p align='center'><strong>Function</strong></p></td></tr><tr><td width='692' colspan='3' valign='top'><p align='center'><strong>Load on Auxiliary Converter no.- 1</strong></p></td></tr><tr><td width='187' valign='top'><p>Oil Cooling Blower-1(OCB-1)</p></td><td width='174' valign='top'><p>Machine Room-1 </p></td><td width='331' valign='top'><p>To cool transformer and SR-1oil in cooling unit-1 by taking air from roof.</p></td></tr><tr><td width='187' valign='top'><p>Oil Cooling Blower-2(OCB-2)</p></td><td width='174' valign='top'><p>Machine Room-2</p></td><td width='331' valign='top'><p>To cool transformer and SR-2 oil in cooling unit-1 by taking air from roof</p></td></tr><tr><td width='692' colspan='3' valign='top'><p align='center'><strong>Load on Auxiliary Converter no.- 2</strong></p></td></tr><tr><td width='187' valign='top'><p>Tr. Motor Blower-1</p></td><td width='174' valign='top'><p>Machine Room-2 </p></td><td width='331' valign='top'><p>To cool bogie &ndash;1 TM group by forced air.</p></td></tr><tr><td width='187' valign='top'><p>Tr. Motor Blower-2</p></td><td width='174' valign='top'><p>Machine Room-1 </p></td><td width='331' valign='top'><p>To cool bogie &ndash;2 TM group by forced air.</p></td></tr><tr><td width='187' valign='top'><p>Transformer oil pump-1</p></td><td width='174' valign='top'><p>Under Truck Below machine room-1</p></td><td width='331' valign='top'><p>To circulate oil from TFP to Cooling Unit-1 &amp; back</p></td></tr><tr><td width='187' valign='top'><p>Transformeroil pump-2</p></td><td width='174' valign='top'><p>Under Truck Corridor-2</p></td><td width='331' valign='top'><p>To circulate oil from TFP to Cooling Unit-2 &amp; back</p></td></tr><tr><td width='187' valign='top'><p>Tr. Converter<br/>Oil Pump-1</p></td><td width='174' valign='top'><p>Machine Room-1<br/>NearSR-1</p></td><td width='331' valign='top'><p>To circulate oil from SR-1 to Cooling Unit-1 &amp; back</p></td></tr><tr><td width='187' valign='top'><p>Tr. Converter<br/>Oil Pump-2</p></td><td width='174' valign='top'><p>Machine Room-2<br/>Near SR-2</p></td><td width='331' valign='top'><p>To circulate oil from SR-1 to Cooling Unit-2 &amp; back</p></td></tr><tr><td width='692' colspan='3' valign='top'><p align='center'><strong>Load on Auxiliary Converter no.- 3</strong></p></td></tr><tr><td width='187' valign='top'><p>Main Compressor-1</p></td><td width='174' valign='top'><p>Under Truck below<br/>Machine room-1</p></td><td width='331' valign='top'><p>To create MR pressure to 10.0 kg/cm2</p></td></tr><tr><td width='187' valign='top'><p>Main<br/>Compressor-2</p></td><td width='174' valign='top'><p>Under Truck below<br/>Machine room-2</p></td><td width='331' valign='top'><p>To create MR pressure to 10.0 kg/cm2</p></td></tr><tr><td width='187' valign='top'><p>Scavenging<br/>Blower-1 </p></td><td width='174' valign='top'><p>Machine Room-1<br/>Near TMB-2 </p></td><td width='331' valign='top'><p>To clean dust from air filters of&nbsp; TMB-2 &amp; OCB-1 </p></td></tr><tr><td width='187' valign='top'><p>Scavenging<br/>Blower-2</p></td><td width='174' valign='top'><p>Machine Room-2<br/>Near TMB-1</p></td><td width='331' valign='top'><p>To clean dust from air filters of&nbsp; TMB-1 &amp; OCB-2</p></td></tr><tr><td width='187' valign='top'><p>Battery<br/>Charger </p></td><td width='174' valign='top'><p>Within Auxiliary<br/>Converter Cubicle</p></td><td width='331' valign='top'><p>To charge battery</p></td></tr></table>",
		"<strong>Ans - </strong><br/>Generally all the 3 Auxiliary converters are loaded equally, but in case of failure of any converter another converter shares its load. In such condition, frequency of aux.Motor drops from 50 Hz to 37Hz. <br/>Load sharing after isolation of any aux. converter. </p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='61' rowspan='2' valign='top'><p>Aux.<br/>Conv-1<br/>Isolate</p></td><td width='102' valign='top'><p>Load on<br/>Aux.Conv-2</p></td><td width='529' valign='top'><p>Oil cooling blower 1-2, Tr.&nbsp; Motor blower 1-2&nbsp;&nbsp; Scavenging blower 1-2</p></td></tr><tr><td width='102' valign='top'><p>Load on Aux.<br/>Conv.-3</p></td><td width='529' valign='top'><p>MCP 1-2 , Transformer pump 1-2&nbsp; Converter pump 1-2 , Battery Charger</p></td></tr><tr><td width='61' rowspan='2' valign='top'><p>Aux.<br/>Conv-2<br/>Isolate</p></td><td width='102' valign='top'><p>Load on<br/>Aux.Conv-1</p></td><td width='529' valign='top'><p>Oil cooling blower 1-2,Tr. Motor blower 1-2&nbsp;&nbsp;&nbsp; Scavenging blower 1-2</p></td></tr><tr><td width='102' valign='top'><p>Load on Aux.<br/>Conv.-3 </p></td><td width='529' valign='top'><p>MCP 1-2 , Transformer pump 1-2 Converter pump 1-2 , Battery Charger</p></td></tr><tr><td width='61' rowspan='2' valign='top'><p>Aux.<br/>Conv-3<br/>Isolate </p></td><td width='102' valign='top'><p>Load on<br/>Aux.Conv-1</p></td><td width='529' valign='top'><p>Oil cooling blower 1-2,Tr. Motor blower 1-2&nbsp;&nbsp;&nbsp; Scavenging blower 1-2</p></td></tr><tr><td width='102' valign='top'><p>Load on Aux. Conv.-2&nbsp; </p></td><td width='529' valign='top'><p>MCP 1-2 , Transformer pump 1-2&nbsp;&nbsp; Converter pump 1-2, Battery Charger</p></td></tr></table>",
		"<strong>Ans - </strong><br/>The auxiliary transformer is located in cubicle-1(HB-1) and supplies following systems with 1-phase power.This circuit is independent of CE and all these auxiliaries work in Driving as well as cooling mode and start as soon as VCB closed.</p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='163' valign='top'><p align='center'><strong>Auxiliary</strong></p></td><td width='150' valign='top'><p align='center'><strong>Location</strong></p></td><td width='379' valign='top'><p align='center'><strong>Function</strong></p></td></tr><tr><td width='692' colspan='3' valign='top'><p align='center'><strong>Single phase 415 Volts </strong></p></td></tr><tr><td width='163' valign='top'><p>Machine Room Blower-1</p></td><td width='150' valign='top'><p align='center'>Machine Room-1</p></td><td width='379' valign='top'><p>To cool machine room by ducting and limit the temperature of control electronics parts below 700C</p></td></tr><tr><td width='163' valign='top'><p>Machine Room Blower-2</p></td><td width='150' valign='top'><p align='center'>Machine Room-2 </p></td><td width='379' valign='top'><p align='center'>-do-</p></td></tr><tr><td width='163' valign='top'><p>Scavenging Blower for Machine room Blower-1</p></td><td width='150' valign='top'><p>Machine Room-1 </p></td><td width='379' valign='top'><p>To clean dust from air filters of Machine Room Blower-1</p></td></tr><tr><td width='163' valign='top'><p>Scavenging Blower for Machine room Blower-2 </p></td><td width='150' valign='top'><p>Machine Room-2 </p></td><td width='379' valign='top'><p>To clean dust from air filters of Machine Room Blower-2</p></td></tr><tr><td width='163' valign='top'><p>Heater Element </p></td><td width='150' valign='top'><p>In Both cab.<br/>Inside Desk</p></td><td width='379' valign='top'><p>To deliver heat for keeping the cab warm</p></td></tr><tr><td width='692' colspan='3' valign='top'><p align='center'><strong>Single phase 110 Volts</strong></p></td></tr><tr><td width='163' valign='top'><p>Crew Fan: 4 nos</p></td><td width='150' valign='top'><p>. 2nos. in Both cabs</p></td><td width='379' valign='top'><p>Crew ventilation</p></td></tr><tr><td width='163' valign='top'><p>Cab Ventilation<br/>Blower- 2 nos.</p></td><td width='150' valign='top'><p>One in Both cab<br/>Inside Desk </p></td><td width='379' valign='top'><p>To expel heat of heater element into the cab. </p></td></tr></table>",
		"<strong>Ans - </strong><br/>There are 5 types of brakes available on this loco.<br/>1. Automatic Train Brake (Pn)<br/>2. Direct Brake (Pn)<br/>3. Parking Brake (Spring Loaded)<br/>4. Anti Spin Brake.(Pn)<br/>5. Regeneration Brakes.(Elect) </p>",
		"<strong>Ans - </strong><br/>In both the cabs one Drivers Brake Controller (DBC) is provided which is the electrical switching equipment.<br/>The function of the driver&rsquo;s brake controller is to generate a variable voltage code in accordance with the position of the controller handle and to perform a number of ancillary electrical functions. A pneumatic valve is incorporated to provide apneumatic emergency brake function in addition to the electronically controlled emergency brake.<br/>This brake is utilized for charging and discharging the B.P. Pressure to apply/release train brake and also loco brakes in conjunction working.<br/>This valve has following 6 positions.<br/>This A-9 is remaining active in active cab only. Once the BL key is rotate from D to OFF, this handle will not functions, but its emergency position will act. </p><p><strong>Handle position Pressure (kg/cm2)</strong><br/>Release 5.4 &plusmn; 0.05 (LPO)<br/>Running 5 &plusmn; 0.05<br/>Initial Application4.60 &plusmn; 0.05 Variable<br/>Full Service 3.35 &plusmn; 0.10<br/>Emergency 0<br/>Neutral0<br/>",
		"<strong>Ans - </strong><br/><strong>Direct Brake (SA-9):</strong><br/>To apply locomotive brakes, Drivers Direct air Brake Valve (SA-9) is provided in both the cabs. The operation of this system is near about same as in case of WAG- 5/7. But unlike WAG-5/7 there are no cocks on inlet as well as outlet pipes of Drivers Direct air Brake Valve (SA-9). Instead of cock the EP valves (pilot valves) are provided which keep the Drivers Direct air Brake Valve (SA-9) in service only in active cab automatically.<br/>As a preventive measure, the handle of Drivers Direct air Brake Valve in rear cab should be kept in release position. Unlike WAG-5/7, separate relay valves are provided for loco brakes through Drivers Direct air Brake Valve and loco brakes through conjunction working. So possibility of total brake failure due to relay valve failure iseliminated.<br/>The Drivers Direct air Brake Valve has two positions; APPLY and RELEASE</p><p><strong>Apply:</strong><br/>When the driver&rsquo;s control handle is moved to the &lsquo;brake on&rsquo; position, air from the main reservoir admits in the out let pipe which (3.5 kg / cm2 max) is further connected tobraking relay valve 58. This pressure operates the relay valve so relay valve again allow the MR pressure waiting at its port to the brake cylinders through 2nos of DCVs and bogie isolating COC. Brake cylinder pressure can be seen in the gauges provided in both the cabs.<br/><strong>Release:</strong><br/>When the driver&rsquo;s control handle is moved towards the &lsquo;release&rsquo; position, it isolates the main reservoir pressure from the relay valve. Simultaneously,allows the pressure from the relay valve to escape to atmosphere through itsexhaust port. As the pressure from relay valve get exhausted, relay valve further disconnect the pressure flow from MR to brake cylinder and simultaneously the pressure of brake cylinder get exhausted to atmosphere through exhaust of relay valve.<br/>Any desired releasing stage for the brake cylinder pressure may be obtained according to the position of the driver&rsquo;s control handle.<br/>The direct brakes are used to apply loco brakes. In WAG-9 it apply on wheel tyre as conventional loco with the pressure of 3.5 Kg/m2.<br/>The brake handle remains active only in active driver Cab.<br/>Start/running interlock (i.e. regression of TE / BE) is initiated when the speed of loco is above 10 KMPH and BC pressure share in gauge by 0.6 kg/cm2 and above..<br/>For isolation of brakes of particular bogie, bogie COC are provided. COC for<br/>bogie -1 is provided below machine room -1 above MCP-1 where as COC for<br/>bogie -2 is provided below machine room -2 above MCP-2</p>",
		"<strong>Ans - </strong><br/><strong>Anti Spin Brakes:</strong><br/>The principal of the anti-spin brake is to provide the traction equipment, with means to obtain a rapid yet light brake application to the driving wheels. Thefriction thus generated between the brake shoes and the tyres immediately absorbs the torque, which is in excess of the value that can be absorbed by thenormal adhesion between the tyre and railhead. The net result is to preventany increase of existing wheel slip.</p><p>The principal advantages are that the slip is prevented or controlled, soavoiding the possibility of damaging the traction equipment, and at the sametime it normally enables the traction power to be maintained so improving andsimplifying the control of the locomotive when operating under conditions whichmay cause wheel slip.</p><p>The anti-spin brake can give an improved adhesion condition between the rail and tyre, due to the cleaning effect of the brake shoe when used with &lsquo;On tread&rsquo; braking.<br/>A further important advantage of the anti-slip brake is that its use often enablesa reduction in the use of sanding.<br/>This device is provided on each bogie behind MCP.<br/>The automatic anti - spin protection is initiated as soon as the ratio betweeneffective tractive/braking effort and requested tractive/braking effort is less than0.5.</p><p>As required, one or more of the following actions is/are initiated:<br/>- Sanders start<br/>- LSP glows<br/>- TE/BE difference is reduced by control electronics.</p>",
		"<strong>Ans -</strong> <br/>If train is running in regenerative (DBR) mode and suddenly regenerative braking gets cut off automatically due to internal fault or VCB tripping, to compensate regenerative braking, blending valve send the MR pressure in thebrake cylinder in proportion. This pressure activates the relay valve (57), further this relay valve allows MR pressure into BC.</p>",
		"<strong>Ans -</strong> <br/><strong>Parking Brake</strong><br/>In 3 phase loco, hand brakes are not provided. For parking the loco a new type brakes are available on this loco, called parking brake. The great feature of parking brake is that, it remains applied to indefinite time as per yourrequirement in absence of air pressure. Its function is just opposite to that of conventional brakes. i.e. it remain release when there is 6 Kg/m2 pressure in parking activator and get applied when pressure exhausted below 3.8 Kg/m2 in parking activator. But the brakes are applied through the same brake block of conventional loco brakes.<br/>Parking brakes are provided on Wheel No.2-6-7-11 in WAG-9 loco.</p><p><strong>Applying Parking Brake</strong><br/>1. Press push button BPPB (&lsquo;A&rsquo; panel), a red lamp illuminated in it. Due towhich 6 Kg/cm2 air in parking activator get exhausted and the PB gaugeshow &lsquo;0&rsquo; kg/cm2 which indicates the application of P.B. (this is possibleonly when CE is ON)<br/>OR<br/>2. Press &lsquo;Apply&rsquo; push button on parking brake valve solenoid 30/22,BPPB red lamp will glow, P.B. pressure gauge show &lsquo;0&rsquo; kg/m2 and PBget applied. (This is possible when there is MR / AR pressure in theloco and lamp will glow if CE is ON)<br/>OR<br/>3. When &lsquo;BL&rsquo; key is moved from &lsquo;D&rsquo; to &lsquo; OFF &lsquo;, parking brakes getautomatically applied through control electronics. BPPB will not beilluminated since CE in OFF but P.B.gauge will show &ldquo;0&rdquo; kg/cm2.</p><p><strong>Releasing Parking Brake:</strong><br/>1. Press BPPB illuminated red button once red lamp will get extinguishedand 6Kg/cm2 pressure enter in parking activators which can be seen in PBgauge indicating that PB are released<br/>OR<br/>2. Press &ldquo;Release&rdquo; push button on parking brake solenoid 30, BPPB redlamp will extinguished, air will be admitted in parking activator andgauge will be shown 6 Kg/cm2 pressure<br/>OR<br/>3. Pull &ldquo;parking brake release spindle&rdquo; provided on parking brake cylinderon wheel No.2,6,7,11.<br/>The lock of PB will open and piston return to release position due to resettingspring at that time. &lsquo;KHUT&rdquo; sound will be heard. </p>",
		"<strong>Ans - </strong><br/>Emergency brakes will apply through brake electronics when:<br/>1. Response from the Vigilance module.<br/>2. Permitted maximum speed being exceeded.<br/>3. Moving of the driver&rsquo;s brake handle to position.<br/>4. Actuation of the emergency brake cock on the assistant driver&rsquo;s side<br/>5. Actuation of the emergency stop push button on the panel A<br/>6. Failure of the electronic brake control system<br/>7. Train parting </p>",
		"<strong>Ans -</strong> There are 19 sub-systems in three phase loco and the names are as following:<br/>SS01- main power,<br/>&nbsp;SS02- Traction bogie-1, <br/>SS03- Traction bogie-2, <br/>SS04- Harmonic filter, <br/>SS05- Hotel load, <br/>SS06- Aux. convertor-1, <br/>SS07- Aux. convertor-2, <br/>SS08- Aux. convertor-3, <br/>SS09- Battery system, <br/>SS10- Brake system, <br/>SS11- Aux. HB-1, <br/>SS12- Aux. HB-2, <br/>SS13- Cab-1, <br/>SS14- Cab-2, <br/>SS15- Fire detection, <br/>SS16- Speedometer, <br/>SS17- FLG-1, <br/>SS18- FLG-2, <br/>SS19- Train bus<br/>",
		"<strong>Ans -</strong> The status code will appear in two digits. The first digit will be 0 or 9 and the second digit will be 0 or 1 or 2,i.e- 00 or 01 or 02 or 91 or 92.<br/>First digit:-&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;0&rsquo; means no sub system isolated<br/>&lsquo;1&rsquo; means at least one sub system isolated.<br/>Second digit:- &lsquo;0&rsquo; means there is no Priority-1 or Priority-2 fault<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;1&rsquo; means there is a Priority-1 fault<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &lsquo;2&rsquo; means there is a Priority-2 fault</p>",
		"<strong>Ans -</strong> Switching OFF MCE is required during following conditions:</p><ul><li>During loco shut down</li><li>During trouble shooting</li><li>During isolated subsystem to make in service</li><li>During resetting/tripping of MCBs of SB-1 &amp; SB-2</li></ul><p>Also Loco pilots desires to switch &lsquo;OFF&rsquo; &amp; &lsquo;ON&rsquo; control electronics to eliminate any transient faults the following sequence shall be followed :</p><ul type='disc'><li>Bring throttle to &lsquo;0&rsquo;. Stop the loco/train, Open VCB and lower pantograph.</li><li>Move BL from &lsquo;D&rsquo; to &lsquo;OFF&rsquo; position and wait for 2 seconds.</li><li>Then move &lsquo;BL&rsquo; from &lsquo;OFF&rsquo; to position &lsquo;C&rsquo; and wait 10 seconds(Till LSDJ, DDS &amp; MEMOTEL light off)</li><li>Then move from &lsquo;C&rsquo; to &lsquo;OFF.&rsquo;</li><li>To switch &lsquo;ON&rsquo; once again move &lsquo;BL&rsquo; from &lsquo;OFF&rsquo; to &lsquo;D&rsquo;</li></ul>",
		"<strong>Ans -</strong><br/>Whenever temperature of control electronics is increases above 700C then lamp LSCE glows on Panel &lsquo;A&rsquo; and throttle will not respond. Control/Coast the train to stop at suitable place like starter etc and do the following.</p><ol start='1' type='1'><li>Inform TLC/SCR regarding cooling.</li><li>Keep the throttle on &lsquo;0&rsquo;.</li><li>Keep SA9- at applied condition and A-9 to emergency.</li><li>Open VCB and lower the pantograph.</li><li>Switch off CE as per procedure.</li><li>Again put &lsquo;BL key&rsquo; from &lsquo;OFF&rsquo; to &lsquo;C&rsquo; and ensure that UBA shows &nbsp;battery voltage and LSDJ glows, Screen is Off - no node information. (Note CE is OFF)</li><li>Now raise the panto, close the VCB- LSDJ will extinguish and loco will energies in cooling mode.</li><li>Machine room blowers &amp; scavenge blowers will start automatically to cool the machine Room. Ensure working of machine room blowers.</li><li>When the machine room temperature goes below 700C then LSCE will&nbsp;extinguish.</li><li>Now Open the VCB, lower the pantograph.</li><li>Put BL from &lsquo;C&rsquo; to &lsquo;Off&rsquo; and &lsquo;off&rsquo; to &lsquo;D&rsquo; and energize loco &amp; resume traction.</li></ol><p><em>Note:-If VCB trips during cooling mode, before closing&nbsp;VCB, check OCR.</em>",
		"<strong>Ans -</strong> </p><ul><li>All employees must take care to avoid the risk of injury to themselves and others and where any maintenance job requires the isolation of the overhead line, staff must check that the overhead line has been isolated.</li><li>Overhead line equipment may be approached only after the catenary has been formerly isolated and earthed.</li><li>Before any examination is started all safety precaution must be carried out.</li><li>Do not use buzzer,bell,megger,or flash test equipment until all circuits which include semiconductor devices have been isolated. </li><li>Do not attempt to make repairs or adjustments in control cubicles or driver&rsquo;s desk when power is on. Ensure that the power supply is disconnected. </li><li>Observe cleaning solvent manufacturer&rsquo;s instruction, as certain solvents may be toxic or flammable.</li><li>Clean lubricating points before applying the recommended lubricant and remove excess after applying new lubricant. </li></ul><ul><li>When welding operations are being carried out on a vehicle, the welding return lead shall be secured as near as possible to the point of welding. All electronic devices shall be individually short circuited.</li><li>Staff must not operate the controls of functional apparatus of a locomotive undergoing maintenance/ testing without first satisfying themselves that there are no persons engaged in any work that locomotive, who can be injured in any way by the operation. </li><li>Caution sign (starting personnel working on locomotive ) to be fitted at the both ends of locomotive.</li></ul>",
		"<strong>Ans- </strong>The following bogie clearances are recommended in WAG9 locomotive.</p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='31' valign='top'><p align='center'>SN</p></td><td width='285' valign='top'><p align='center'>Clearance</p></td><td width='158' valign='top'><p align='center'>Manufcturing(design) Limits (mm)</p></td><td width='158' valign='top'><p align='center'>Service limits (mm)</p></td></tr><tr><td width='31' valign='top'><p>1.</p></td><td width='285' valign='top'><p>Vertical clearance between Axle box and Bogie frame </p></td><td width='158' valign='top'><p>30 to 35 </p></td><td width='158' valign='top'><p>27 to 35</p></td></tr><tr><td width='31' valign='top'><p>2.</p></td><td width='285' valign='top'><p>Lateral&nbsp; clearance between Axle box and Bogie frame</p></td><td width='158' valign='top'><p>15 to 19</p></td><td width='158' valign='top'><p>15 to 22</p></td></tr><tr><td width='31' valign='top'><p>3.</p></td><td width='285' valign='top'><p>Vertical clearance between bogie frame and under frame</p></td><td width='158' valign='top'><p>35 to 60</p></td><td width='158' valign='top'><p>32 to 60</p></td></tr><tr><td width='31' valign='top'><p>4.</p></td><td width='285' valign='top'><p>Lateral clearance between bogie frame and under frame</p></td><td width='158' valign='top'><p>45 to 50</p></td><td width='158' valign='top'><p>45 to 55</p></td></tr></table>",
		"<p><strong>Ans -</strong> The <strong>limits for wheel diameter difference </strong>WAG9 locomotives have now been finalized as follows.</p><p>&nbsp;</p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='139' valign='top'><p><strong>For Wheels </strong> </p></td><td width='293' valign='top'><p><strong>Preferable limit at the time of</strong><br/><strong>wheel re-profiling/for new wheel</strong></p></td><td width='216' valign='top'><p><strong>Permissible service</strong><br/><strong>Limit </strong> </p></td></tr><tr><td width='139' valign='top'><p>On same axle </p></td><td width='293' valign='top'><p>0.5 mm </p></td><td width='216' valign='top'><p>2.5 mm </p></td></tr><tr><td width='139' valign='top'><p>On same bogie </p></td><td width='293' valign='top'><p>2 mm </p></td><td width='216' valign='top'><p>4 mm </p></td></tr><tr><td width='139' valign='top'><p>On same loco </p></td><td width='293' valign='top'><p>15 mm </p></td><td width='216' valign='top'><p>20 mm </p></td></tr></table><p><strong>Root Wear and Flange Wear limit of WAG9 loco is 6 mm and 3 mm respectively.</strong></p>",
		"<strong>Ans - </strong></p><p>1. The Fibre optic end terminations are of extremely high quality and even aspeck of dust or smudge on it can spoil the connection. Therefore,<br/>a)End connections must be closed with protective cap when not in use.<br/>b)Never scratch or even touch the fibre optic surface.<br/>2. Connection of the fibre optic cables should not be pulled as this can damagethe cable and the connector itself. The mechanical force must be limited toless than 25N. It should be held at its connectors while removing from thePCB.<br/>3. The minimum bending radius of the fibre optic cable should be 50 mm.</p>",
		"<strong>Ans &ndash;</strong> <br/>The traction converter is equipped with an interlocking system to ensure that the converter doors can<br/>only be opened after the power capacitors are discharged and the DC-link is earthed. The keys for opening the traction converter doors are released according to the procedure below.</p><p>IMAGELINK</p><p>1. Close the air supply valve to the pantograph - &ldquo;key A&rdquo; is released<br/>2. Insert and turn &ldquo;key A&rdquo; in the VCB earthing switch<br/>3. Turn the earthing switch - &ldquo;keys B&rdquo; are released<br/>4. Insert and turn &ldquo;key B&rdquo; in key multiplier 1 - &ldquo;keys C&rdquo; are released<br/>5. <strong>Wait at least 10 minutes before turning earthing switch (-S100)</strong><br/>6. Insert and turn &ldquo;key C&rdquo; in the earthing switch of the traction converter -&ldquo;key D&rdquo; is released<br/>7. Insert and turn &ldquo;key D&rdquo; in key multiplier 2 - &ldquo;keys E&rdquo; are released<br/>8. Insert and turn &ldquo;keys E&rdquo; in the door locks of the traction converter</p>",
		"<strong>Ans - </strong></p><table border='1' cellspacing='0' cellpadding='0' width='714'><tr><td width='180'><p align='center'><strong>Maintenance Schedule</strong> </p></td><td width='240'><p align='center'><strong>Periodicity</strong> </p></td><td width='294'><p align='center'><strong>Duration</strong> </p></td></tr><tr><td width='180'><p align='center'>Trip inspection (TI)</p></td><td width='240'><p align='center'>45 days </p></td><td width='294'><p align='center'>4 hrs</p></td></tr><tr><td width='180'><p align='center'>IA</p></td><td width='240'><p align='center'>90 days</p></td><td width='294'><p align='center'>4 hrs</p></td></tr><tr><td width='180'><p align='center'>IB</p></td><td width='240'><p align='center'>180 days</p></td><td width='294'><p align='center'>6 hrs</p></td></tr><tr><td width='180'><p align='center'>IC</p></td><td width='240'><p align='center'>270 days</p></td><td width='294'><p align='center'>8 hrs</p></td></tr><tr><td width='180'><p align='center'>MOH</p></td><td width='240'><p align='center'>18 months</p></td><td width='294'><p>6 working days /8 working days for 2nd&nbsp;MOH </p></td></tr><tr><td width='180'><p align='center'>IOH</p></td><td width='240'><p align='center'>6 years&nbsp;<u>+</u>&nbsp;6 months or 12 lakh kms. whichever is earlier.</p></td><td width='294'><p align='center'>11 working days</p></td></tr><tr><td width='180'><p align='center'>POH</p></td><td width='240'><p align='center'>12 years&nbsp;<u>+</u>&nbsp;6 months or 24 lakh kms. whichever is earlier.</p></td><td width='294'><p align='center'>28 working days</p></td></tr></table>",
		"<strong>Ans - </strong><br/>i. Check the wellbeing and presence of the safety sling. <br/>ii. Check the push /pull rod pivot heads for damage. <br/>iii. Examine the traction link assembly for signs of damage. Anydefective item should be renewed.<br/>iv. Check the fastener at the traction ends and those retaining thetraction rod for security. If a fastener is loose, it must berenewed and tightened to the specified torque. Ensureintactness of the locking plate.<br/>v. RDPT of traction bar at end (flange) portion &amp; V-Ring housing flange. <br/>vi. Examine limit chain and links for wear, corrosion or damage.<br/>vii. Inspect the safety slings, pins and R clips for wear and damage. <br/>vii. Check Aclathan / Vulkollon ring against any crack or shifting. </p>",
		"<strong>Ans - </strong><br/>i.Check the brake rigging for loose, damaged or worn out parts.Rectify as required.</p><p>ii. Examine the bogie frame, transom beam &amp; yaw damper basefor signs of crack/damage.</p><p>iii. Examine all bogies mounted equipments (Including earthingstraps) for signs of damage and security of fastening.</p><p>iv. Inspect the rubber bumps for damage deterioration. Replace ifrequired.</p><p>v. Inspect the brake rigging rotation points and component contactsurfaces. Rectify any faults found.</p><p>vi. Check the brake cylinder piston stroke.</p><p>vii Check the TBU/PBU for air leakage. </p><p>viii Test Loco Brake Power. Refer RDSO&rsquo;s Maintenance InstructionNo.RDSO/ELRS/MI/0003 Rev.(&lsquo;0&rsquo;)</p><p>ix. Inspect the bogie body safety pin eyehole at the bogie frame forwear or cracks.</p><p>x. Check the pneumatic pipeline systems for leakage. </p><p>xi. Maintain the vertical &amp; lateral clearances (Primary &amp; secondary)Refer RDSO&rsquo;s technical circular no. ELRS/TC/0082 (Rev.&rsquo;0&rsquo;).</p><p>xii. Check the earthing shunts provided on bogie and body. </p><p>xiii. Check intactness or axle box cover bolts. </p><p>xiv. Inspect brake gear for any worn out loose, damaged, hanging ordragging parts. Confirm intactness.</p><p>xv. Test for correct operation of the brake cylinder actuator unit.<br/>xvi. Check the proper tightness of parking brake &amp; service brakepneumatic pipes.</p><p>xvii. Check the external hitting marks &amp; physical damage on thebrake cylinder actuator unit.</p><p>xviii. Check the condition of parking brake cylinder bellows. If damaged, replace them. </p><p>xix. On parking brake cylinder pulling spindle &amp; ring should be intact.</p><p>xx. Check proper functioning of parking brake &amp; service brakecylinder.</p><p>xxi. Check the operation (manual releasing) of the parking brakes.</p><p>xxii. Check the bogie isolating cock, should be in proper position. </p>",
		"<strong>Ans - </strong></p><p>i. Visually examine the entire head structure of the pantograph including horn, wear stripes &amp; support assemblies for crack.Replace any defective items.</p><p>ii. Non-destructive testing like DPT of critical pantograph sub-equipments like support assembly be done.</p><p>iii. Check for any bent or bowed pans, leakage in operating cylinder &amp; proper functioning of dampers &amp; pan springs.</p><p>iv. Check that the pan head locking pins springs are in place and secure. Check that the head moves freely on its mounting pins attached to the apex frame. If movement is not free, check that the head is not twisted, the side beam are not bent/twisted &amp; mounting pins are not loose or bent.</p><p>v. Check tightness of the shunt connecting screws. When a loose screw is found the shunt should be disconnected from the head&amp;/or the pantograph frame, the mating surface cleaned &amp; the shunt reconnected with new screws.Check all shunts for frayed strands and renew any shunt in which 25% or more of the strands are frayed.<br/>vi. Examine for any cracks on the body &amp; the bow assembly. <br/>vii. Check for proper operation &ndash; raising &amp; lowering &amp; adjust the raising &amp; lowering time if required.<br/>viii. Check and adjust the contact force with the help of 9 kg mass. <br/>ix. Lubricate all grease points using grease gun. <br/>x. Clean foot mounting insulators &amp; check for any cracks, chipping off etc. Apply specified grease and polish with a soft lint free cloth.<br/>xi. Check the dampers of pantograph for any oil leakage. <br/>xii. Check the pneumatic pipeline on roof for any air leakage with soap solution.</p>",
		"<strong>Ans -</strong> </p><p>i. Read off the oil level on the gauge situated on the conservator.Top up the oil as necessary and check for any signs of leakage. Clean the gauge with dry cloth.</p><p>ii. Inspect the colour of the silica gel. If it is pink, remove the filterfrom the locomotive. Dry the silica gel in oven at 150 degree Cand replace.</p><p>iii. Examine the H.V. bushing for signs of damage, burning etc.Replace if defective.</p><p>iv. Examine the flanges of the pipe couplings and flexible hose thatlink the transformer and conservator.</p><p>v. Check the availability of hosepipe over the oil pipecompensators.</p><p>vi. Check the main TFP and its protection cover for any damage,crack &amp; oil leakage.</p><p>vii. Check the oil leakage from TFP bushing. </p><p>viii. Check the deformity of TFP drain cock protection cover guard ifdeformed replace it</p><p>ix. Perform the sample test on transformer oil. Check specific valueof BDV, DGA, moisture and acidity.</p><p>x. Check visually the transformer foundation bolt and Nylock Nutfor proper locking.</p><p>xi. Check the earthing cable. </p><p>xii. Clean and visually inspect the insulator and connection oftransformer and converter for crack &amp; flashed mark.</p><p>xiii. Visually inspect the condition of oil cooling metallic pipes, checkfor leakage / damage &amp; check all fixing clamps. </p>",
		"<strong>Ans - </strong><br/>i. Check the oil level indicator situated on the conservator (Expansion Tank). If the oil is below the minimum mark-top up with the specified oil. Check for any signs of leakage.</p><p>ii. Visually examine Oil pipe joints for leaks, loose or missing screws and correct as necessary.</p><p>iii. Examine the two flange joints for leaks, loose or missing screws. Check gaskets/oil seals, if dismantling is required.&nbsp; <br/>iv. Examine all electrical equipment of traction converter for signs of dirt, corrosion, damage etc. Remove all dust/dirt depositsfrom the connection insulators.</p><p>v. Check the cable connection of Sichem connectors of differentialamplifier provided below SR oil pump.</p><p>vi. Clean the isolating blade and spring contact of earthingswitch.Lightly lubricate with the specified grease.</p><p>vii. Clean DC link capacitors by blowing after opening side cover.Check that there is no sign of leakage from the capacitors.<br/>viii. Clean resonance circuit capacitor. </p><p>ix. Cleaning by Vacuum cleaner.</p><p>x. Check the tightness of SR electronics PCB.</p><p>xi. Ensure sealing of incoming cable gland of control card rack to avoid dust entry.</p><p>xii. Check the condition of silica gel. If pink replace with dried silica gel.</p><p>xiii. BDV and DGA test of converter oil to be done. </p><p>xiv. Check the ventilation fans of traction converters.</p>",
		"<strong>Ans - </strong><br/>i. Examine all traction motors for signs of damage, dents or otherdefects caused by ballast. Check air outlets are not obstructedin any way.</p><p>ii. Check traction power cables, speed sensor and temperaturesensor cables and ensure that they are not chamfered ordamaged in any way.</p><p>iii. Lubricate the both end bearings using a grease gun withspecified grease.</p><p>iv Tightness of both end cover bolts of Traction Motor. </p><p>v. Check the intactness of the junction box cover and bolt.</p><p>vi. Check the condition of bearing by seeing the grease, whichcomes out from grease inlet. Check the condition of grease too.</p><p>vii. The locking plate arrangement of support plate, if not availableplease provide.</p><p>viii. Check the condition of traction motor spheriblocks. Replace ifrequired.</p><p>ix. Check the condition of speed pulse generator unit on TM (NDE)for any grease ingress.</p><p>x. Check the suspension tube bearing grease (NDE end) &amp; do thegreasing.(FOR WAG9 /WAG9H/WAP7)</p><p>xi. Open TM junction box at body side and check the tightness of connections.</p><p>xii. Check the condition of bellows and replace if required.</p>",
		"<strong>Ans -</strong> <br/>i. Examine the roof-mounted resistor for any signs of damage or overheating or presence of foreign materials and clean debris away from the resistor.</p><p>ii. Check electrical connections are secure. </p><p>iii. Clean the filter resistor and its insulators. </p><p>iv. Visually inspect the contact tips of contactors for signs of arcing damage. Repair / replace the defective parts.</p><p>v. Visually inspect the capacitor elements inside the cubicle, checking for signs of damage.</p><p>vi. Perform functional checks ensuring the main and Aux. Contacts operate correctly.</p>",
		"<p><strong>Ans -</strong> <br/>Circuit board assemblies must always be handled at properly designated work areas.<br/>Designated work areas must ensure safety from ESD. Areas of main concern include:<br/>A. Proper grounding methods.<br/>B. Static dissipation of work surfaces (e.g. work table).<br/>C. Wrist strap with grounding wire.<br/>D. Static dissipation of floor surfaces.<br/>E. Operation of compressed air guns.<br/>F. Conductive shoes grounding the human body.<br/>G. Antistatic work suit for person.<br/>The above concerns should be checked periodically for continued safety.<br/>&nbsp;Designated work areas must be kept free of static generating materials such as Styrofoam, vinyl, plastic, fabrics etc.<br/>Whenever handling a circuit board assembly the operator must be properly grounded by one of the following:<br/>1. Wearing a wrist strap connected to earth ground.<br/>2. Wearing heel grounders and have feet on a static dissipative floor surface.<br/>3. Circuit board assemblies should be handled by the edges. Do not touch the circuits or components.<br/>4. Components should be handled by the edges when possible. Do not touch the component leads.<br/>5. Antistatic packet normally used for packaging for PCB&rsquo;s is having nonconductive inside surface &amp; highly conductive outer surface. Therefore, in no instance PCB should be kept on antistatic packet after removing the card from the packet.",
		"<strong>Ans -</strong> </p><table border='1' cellspacing='0' cellpadding='0'><tr><td width='49' valign='top'><p align='center'><strong>S.N.</strong></p></td><td width='416' valign='top'><p align='center'><strong>Name of PCB</strong></p></td><td width='233' valign='top'><p align='center'><strong>Slot no.</strong></p></td></tr><tr><td width='49' valign='top'><p>1.</p></td><td width='416' valign='top'><p>Power Supply</p></td><td width='233' valign='top'><p>AB/CD Slot</p></td></tr><tr><td width='49' valign='top'><p>2.</p></td><td width='416' valign='top'><p>Diagnostic Computer </p></td><td width='233' valign='top'><p>U slot</p></td></tr><tr><td width='49' valign='top'><p>3.</p></td><td width='416' valign='top'><p>Single Routine Board</p></td><td width='233' valign='top'><p>E Slot</p></td></tr><tr><td width='49' valign='top'><p>4.</p></td><td width='416' valign='top'><p>Single board Computer</p></td><td width='233' valign='top'><p>G/N/S Slot</p></td></tr><tr><td width='49' valign='top'><p>5.</p></td><td width='416' valign='top'><p>Analog I/O Board</p></td><td width='233' valign='top'><p>F Slot</p></td></tr><tr><td width='49' valign='top'><p>6. </p></td><td width='416' valign='top'><p>Display Computer (DDA)</p></td><td width='233' valign='top'><p>HI slot</p></td></tr><tr><td width='49' valign='top'><p>7.</p></td><td width='416' valign='top'><p>Digital I/O Board</p></td><td width='233' valign='top'><p>J/L/O/Q Slot</p></td></tr><tr><td width='49' valign='top'><p>8.</p></td><td width='416' valign='top'><p>Bus Administrator</p></td><td width='233' valign='top'><p>T slot</p></td></tr><tr><td width='49' valign='top'><p>9.</p></td><td width='416' valign='top'><p>Multiple Redundant bus Coupler</p></td><td width='233' valign='top'><p>W Slot</p></td></tr><tr><td width='49' valign='top'><p>10. </p></td><td width='416' valign='top'><p>Train Bus Administrator</p></td><td width='233' valign='top'><p>YZ slot</p></td></tr></table>",
		"<strong>Ans -</strong><br/><strong>The Concept </strong><br/>Power is taken from the OHE through pantograph to the Transformer of locomotive which is provided with a hotel load winding of 945 kVA, at nominal voltage of 750 V single-phase. <br/>750 Volts single-phase supply from Hotel Load winding will be fed to IGBT based Hotel Load Converter, which will give 750 Volts 3-phase 50 Hz supply as output, for feeding the hotel load of the train. <br/>Converter output will be used to at suitable voltage levels using step down transformers to operate the lights, fans, air conditioning, water raising apparatus of the coaches and the pantry car equipment. <br/>Rajdhani /Shatabdi rake shall be used for HOG power supply scheme.</p><p><strong>Merits </strong> <br/>No air or noise pollution which is generated by power cars.<br/>Highest reliability as compared to Self Generation (SG) and End on Generation (EOG) system due to reduced number of equipments and devices. <br/>Low maintenance requirement.<br/>Reduced dead weight as compared to SG &amp; EOG system.<br/>Possibility of Elimination of under-slung equipments like alternator &amp; battery in conventional coaches thus enhanced safety. <br/>One set of Diesel Alternator (DA) will not be required. Other set would be required only as standby mode for supply. One DA set will be removed from the power car which will pave space for commercial use. <br/>The hotel load is supplied by a separate secondary winding of the main transformer: <br/>Voltage: 750 V AC <br/>Frequency: 50 Hz <br/>Power: 850 kVA</p><p>The spring-loaded hotel load supply switch BLHO&rdquo; in the driver&rsquo;s cab switches contactor 32 via the MCE. <br/>When it is closed, the yellow hotel load supply indication lamp &ldquo;LSHO&rdquo; lights up in the cab. The hotel load is connected to the train via the four-pin hotel load sockets. There are two hotel load sockets outside at both ends of the loco.</p>",
		"<strong>Ans -</strong> <br/>Most faults are detected by the relevant monitoring equipment and are reported to the train driver by indication lamps or displays on the screen. A distinction is made between 2 priorities of fault messages:<br/><strong>Faults with Priority 1 </strong> <br/>- The action to be taken is entirely clear <br/>- The action to be taken must be initiated immediately <br/>- A protective action is initiated (VCB off). </p><p><strong>Faults with Priority 2 </strong> <br/>- The action to be taken is not entirely clear. <br/>- The action to be taken does not have to be initiated immediately. <br/>- The faults can be remedied manually by the train driver. </p><p>If a fault message appears on screen, the yellow illuminated push button &quot;BPFA&quot; lights up. If this is a fault message of priority 1, the red indication lamp &quot;LSFI&quot; starts flashing at the same time. <br/>If a fault message with priority 1 is displayed, a fault message with priority 2 is suppressed on the screen. <br/>A fault message with priority 2 remains on the screen until it is overwritten by a fault message with priority 1 or by a subsequent fault with priority 2. </p>"
    ]
];