var objective_topic=["Mechanical : Objective Question"];
var subjective_topic=["Mechanical : Subjective Question"];

var objective_question=[
    [
		"1: What type of bogie is used in wag-7 loco as per wheel arrangement? ",
		"2: What type of bogie is used in WAG5 loco based on bogie design? ",
		"3: What type of bogie is used in WAG7 loco based on bogie design? ",
		"4: What type of bogie is used in WAP4 loco based on bogie design? ",
		"5: what is the new assembly wheel distance between the inside gauge face of the rim? ",
		"6: what is the serviceable wheel distance between the inside gauge face of the rim? ",
		"7: What Is The new wheel Diameter In WAG-5 Loco? ",
		"8: What Is The new wheel Diameter In WAG-7 Loco? ",
		"9: What Is The Permissible Diameter Of Wear Adopted Wheel In WAP-4 loco? ",
		"10: What Is The Permissible Diameter Of Wear Adopted Wheel In WAG-7 loco? ",
		"11: What is The permissible Longitudinal Clearance middle and end axle per axle box In WAG-5Loco (new condition)? ",
		"12: What is the permissible service limit of Longitudinal Clearance middle and end axle per axle box In WAG-5 Loco? ",
		"13: What is the permissible limit of Lateral Clearance end axle per axle In WAG-5 Loco? ",
		"14: What is the permissible limit of Lateral Clearance middle axle per axle In WAG-5 Loco? ",
		"15: What is the minimum and maximum Lateral Clearances end axle per axle In WAP-4 Loco? ",
		"16: What is the minimum and maximum Lateral Clearances end axle per axle In WAP-4 Loco? ",
		"17: What is the minimum and maximum Lateral Clearances middle axle per axle In WAP-4 Loco? ",
		"18: What is the longitudinal clearance per axle box in WAG-7 loco in new condition? ",
		"19: What is the service limit of longitudinal clearance per axle box in WAG-7 loco? ",
		"20: What is the lateral clearance of middle axle box per axle in WAG-7 loco in new condition? ",
		"21: What is the service limit of lateral clearance of middle axle box per axle in WAG-7 loco? ",
		"22: What is the lateral clearance of end axle box per axle in WAG-7 loco in new condition? ",
		"23: What is the lateral clearance of end axle box per axle in WAG-7 loco in new condition? ",
		"24: What is the service limit of lateral clearance of end axle box per axle in WAG-7 loco? ",
		"25: What is the lateral clearance of end axle box per axle in WAP-4 loco in new condition? ",
		"26: What is the lateral clearance of middle axle box per axle in WAP-4 loco in new condition? ",
		"27: What is the service limit of lateral clearance of end axle box per axle in WAP-4 loco? ",
		"28: What is the service limit of lateral clearance of middle axle box per axle in WAP-4 loco? ",
		"29: What is the longitudinal clearance of middle and end axle box per axle in WAP-4 loco in new condition? ",
		"30: What is the service limit of longitudinal clearance of middle and end axle box per axle in WAP-4 loco? ",
		"31: What Is The Slope In The Wheel Tread? ",
		"32: What Is The Thickness Of The Wheel Flange In Its Base? ",
		"33: What Is The Maximum Root Wear Permissible For A Wear Adopted Wheel? ",
		"34: What Is The Maximum Flange Wear Permissible For A Wear ",
		"35: What Is The Gap To Be MaintainedBetween Wheel And Brakeshoe? ",
		"36: IN WAG 5 loco, the pivot carries approximately _____% of the vertical load While the two load bearers share the remaining ____% of the vertical load. ",
		"37: What Is The Distance Between Front And Middle Axle Of WAG-7 Loco? ",
		"38: What Is The Distance Between Middle And Rear Axle Of Wag-7 Loco? ",
		"39: What Is The Wheel Difference Permissible Between Two Bogies of WAP4 loco? ",
		"40: What Is The Wheel Difference Permissible in same axle of WAP4 loco? ",
		"41: What Is The Wheel Difference Permissible in same bogie of WAP4 loco? ",
		"42: What Is The Wheel Difference Permissible Between Two Bogies of WAG5/WAM4 loco? ",
		"43: What Is The Wheel Difference Permissible in same axle of WAG5/WAM4 loco? ",
		"44: What Is The Wheel Difference Permissible in same bogie of WAG5/WAM4 loco? ",
		"45: What Is The Wheel Difference Permissible Between Two Bogies of WAG7 loco? ",
		"46: What Is The Wheel Difference Permissible in same axle of WAG7 loco? ",
		"47: What Is The Wheel Difference Permissible in same bogie of WAG7 loco? ",
		"49: What Is The Piston Stroke length Of Brake Cylinder in WAG5/WAM4loco? ",
		"50: What Is The Piston Stroke length Of Brake Cylinder in WAG-7loco? ",
		"51: What Is The Piston Stroke length Of Brake Cylinder in WAP-4loco? ",
		"52: How Many Nos. Of Cattle Guard Foundation Bolts Required? ",
		"53: What Is The Size Of Cattle Guard Foundation Bolt? ",
		"54: Tm Nose Gap With Its Sandwich Pad Is___________ ",
		"55: Total numbers Of Fixation Bolts For Gear-case Required Are ______ ",
		"56: what is the Capacity Of Lubricant Oil In Suspension Bearing? ",
		"57: what is the Capacity Of Lubricant In Gear case? ",
		"58: What is the gear ratio of WAG5/WAM4 normal speed loco? ",
		"59: What is the gear ratio of WAG5/WAM4 high speed loco? ",
		"60: What is the gear ratio of WAG7 loco? ",
		"61: What is the gear ratio of WAP4 loco? ",
		"62: Which lubricant is used in axle box? ",
		"63: Which lubricant is used in gear case? ",
		"64: What is the axle load 0f WAG7 loco? ",
		"65: What is the gap between sander nozzle to wheel face? ",
		"66: How many primary vertical dampers are there in WAG7 loco? ",
		"67: How many secondary lateral dampers are there in WAG7 loco? ",
		"68: What is the buffer height from rail level to buffer face Centre? ",
		"69: What is the rail guard height from rail level in WAP4/WAG7 loco? ",
		"70: Tools Used To Measure Wheel Flange Is-- ",
		"71: Cast Iron Brake Shoe Is Being Replaced By ________ ",
		"72: In Comparison to Cast Iron Brake Block Coefficient OfFriction Of Composite Brake Block Is ________ ",
		"73: NosOf Side Bearer In Wag-7 Loco Is ________ ",
		"74: Traction Motor Fitted With Bogie In Axle Hang NoseSuspended System In Loco— ",
		"75: No. Of EOT Crane Required For Lifting WAG-5 Loco Is ___________ ",
		"76: What is the sander nozzle height from rail level? ",
		"77: Hand Brake Is Connected In WAG-7 Loco with Brake cylinder No______ ",
		"78: Good brake power means WAG-5 loco should not move on _____ notch ",
		"79: Good brake means WAP4 loco should not move on ____ amps ",
		"80: WAG7/WAG5 loco should move on _____ amps ",
		"81: Brake will apply on wheel No.______ if hand brake applied by crew - ",
		"82: No. of sand boxes provided on WAG7 - ",
		"83: WAG-5 loco having ____ centre pivots and _____ side bearers - ",
		"84: Number of gear cases provided in WAG-5 loco is - ",
		"85: Number of sets of helical springs provided in WAG5 loco is - ",
		"86: Number of sets of equalizing beams provided in WAG5 loco is – ",
		"87: Number of brake cylinders in WAP-4 loco is - ",
		"88: When hand brake applied, brakes apply on WAG-7 loco is - ",
		"89: When hand brake applied on WAP-4, brakes apply on wheel no -"
	]
];

var objectiveoptions=[
    [
		["a) B-B ","b) Bo-Bo ","c) Co-Co "],
		["a) Tri mount Bogie ","b) Hi adhesion bogie ","c) Flexi Coil Bogie "],
		["a) Tri mount Bogie ","b) Hi adhesion bogie ","c) Flexi Coil Bogie "],
		["a) Tri mount Bogie ","b) Hi adhesion bogie ","c) Flexi Coil Bogie "],
		["a) 1596 +_0.5 mm ","b)1690 mm ","c) 1690 +_1.5 mm "],
		["a) 1596 -0.5 mm/+3 mm ","b) 1690-0.5 mm/+3 mm ","c) 1690 +_1.5 mm "],
		["a) 1099 (+5/-5) mm ","b) 1092 (+5/-0) mm ","c) 1090 (+5/-0) mm"],
		["a) 1099 (+5/-5) mm ","b) 1090 (+5/-0) mm ","c) 1092 (+5/-0) mm "],
		["a) 1016 mm ","b) 1010 mm ","c)1006 mm "],
		["a) 1010 mm ","b) 1016 mm ","c)1006 mm "],
		["a) 0.4-4 mm ","b) 0.4- 1.9 mm ","c) 5- 15 mm "],
		["a) 1.5 - 5 mm ","b) 0.4- 1.9 mm ","c) 5- 15 mm "],
		["a) 6-12 mm ","b) 1.5-5 mm ","c) 5- 15 mm "],
		["a) 6-12 mm ","b) 25-31 mm ","c) 5- 15 mm "],
		["a) 6-12 mm ","b) 1.5-5 mm ","c) 15.4 – 18.2 mm "],
		["a) 6-12 mm ","b) 1.5-5 mm ","c) 15.4 – 24.0 mm "],
		["a) 2.5-6.0 mm ","b) 3.6-7.2 mm ","c) 5.0-8.5mm "],
		["a) 4.5- 6.0 mm ","b) 6.5-12.5 mm ","c) 2- 4 mm "],
		["a) 4.5- 6.0 mm ","b) 2- 6 mm ","c) 6-12 mm "],
		["a) 4.5- 6.0 mm ","b) 2.4- 6 mm ","c)6-12 mm "],
		["a)2.4- 11.5mm ","b) 2.4- 6.0 mm ","c) 6-12 mm "],
		["a) 6-12 mm ","b) 22- 25.2mm","c) 8-16 mm "],
		["a) 4.5- 6.0 mm ","b) 2.4- 6 mm ","c) 22.0-25.2 mm "],
		["a) 22- 30.7mm ","b)22- 30 mm ","c) 6-12 mm "],
		["a) 6-12 mm ","b) 15.4 – 18.2mm ","c) 8-16 mm "],
		["a) 4.5- 6.0 mm ","b) 2.4- 6 mm ","c) 3.6-7.2 mm "],
		["a) 15.4- 24.0mm ","b)22- 30 mm ","c) 6-12 mm "],
		["a) 3.6- 12.0mm ","b)22- 30 mm ","c) 6-12 mm "],
		["a) 4.5- 6.0 mm ","b) 2.4- 6 mm ","c) 0.4-2 mm "],
		["a) 0.4-4mm ","b)22- 30 mm ","c) 6-12 mm "],
		["a) 1 in 20 ","b) 1 in 30 ","c) 1 in 40 "],
		["a) 30.5 mm ","b) 37.5 mm ","c) 35.5 mm "],
		["a) 1.5 mm ","b) 3 mm ","c) 6 mm "],
		["a) 1.5 mm ","b) 3 mm ","c) 6 mm "],
		["a) 10 mm ","b) 15 mm ","c) 6 mm "],
		["a) 60/40 ","b) 70/30 ","c) 50/50 "],
		["a) 1800 mm ","b) 1900 mm ","c) 1850 mm "],
		["a) 1800 mm ","b) 1850 mm ","c) 1900 mm "],
		["a) 15-20 mm ","b) 2-5 mm ","c) 4-10 mm "],
		["a) 0.5-1.5 mm ","b) 2-5 mm ","c) 3-6 mm "],
		["a) 0.5-1.5 mm ","b) 2-5 mm ","c) 3-6 mm "],
		["a) 15-25 mm ","b) 2-5 mm ","c) 4-10 mm "],
		["a) 0.5-2.5 mm ","b) 2-5 mm ","c) 3-6 mm "],
		["a) 0.5-1.5 mm ","b) 2-8 mm ","c) 3-6 mm "],
		["a) 2-5 mm ","b) 15-25 mm ","c) 4-10 mm "],
		["a) 0.5-2.5 mm ","b) 2-5 mm ","c) 3-6 mm "],
		["a) 0.5-1.5 mm ","b) 3-6 mm ","c) 2-8 mm "],
		["a) 95-105 mm ","b) 97-107 mm ","c) 68-78 mm "],
		["a) 95-105 mm ","b) 107- 117 mm ","c) 68-78 mm "],
		["a) 95-105 mm ","b) 107- 117 mm ","c) 68-78 mm "],
		["a) 24 ","b) 12 ","c) 8 "],
		["a) M 20X75 MM ","b) M24X90 ","c) M20X60 "],
		["a) 18 mm ","b) 10 mm ","c) 50 mm "],
		["a) 6 ","b) 10 ","c) 8 "],
		["a) 22 LITRES ","b) 20 liters","c) 18 liters "],
		["a) 22 LITRES ","b) 20 liters","c) 18 liters "],
		["a) 15:62 ","b) 16:65","c) 21:58 "],
		["a) 15:62 ","b) 16:65","c) 21:58 "],
		["a) 15:62 ","b) 16:65","c) 21:58 "],
		["a) 15:62 ","b) 23:58","c) 21:58 "],
		["a) Servogem RR3","b) Turbonil T77","c) Both "],
		["a) Servogem RR3","b) Turbonil T77","c) Both "],
		["a) 23 T","b) 20.50 T ","c) 32 T "],
		["a) 30-40mm ","b) 35-40 mm","c) 50-60 mm "],
		["a) 8Nos.","b) 4 Nos. ","c) 12 nos. "],
		["a) 8Nos. ","b) 4 Nos.","c) 12 Nos. "],
		["a) 1030 – 1105 mm ","b) 1000- 1100 mm ","c) 1050- 1150 mm "],
		["a) 103- 110 mm ","b) 104-121mm ","c) 104-119 mm "],
		["a) Distance Gauge ","b)Profile Gauge ","c)Dia. Gauge. "],
		["a) Ferrobestus ","b) Mild Steel ","c) None "],
		["a) Less ","b)Equal ","c) More "],
		["a) 4 ","b) 8 ","c) 2 "],
		["a) WAG-5 ","b) WAG-7 ","c) Both "],
		["a) 2 ","b) 4 ","c) 3 "],
		["a) 50- 60 mm ","b) 60-70mm ","c) 40-50mm "],
		["a) 1 ","b) 3 ","c) 2 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 500 ","b) 600 ","c) 700 "],
		["a) 600 ","b) 700 ","c) 800 "],
		["a) 1,3 ","b) 2,3 ","c) 2,4 "],
		["a) 4 ","b) 8 ","c)12 "],
		["a) 2 & 4 ","b) 4 & 2 ","c) 2 & 6 "],
		["a) 4 ","b) 6 ","c) 8"],
		["a) 16 ","b) 20 ","c) 24"],
		["a) 6 ","b) 12 ","c) 8"],
		["a) 8 ","b) 4 ","c) 12"],
		["a) Both sides of wheel No.2 ","b) One side of wheel No.4 ","c) both "],
		["a) 2 & 4 ","b) 2 ","c) 1"]
	]
];

var objectiveAnswer=[
    [
		3,1,2,3,1,1,2,3,1,2,2,1,1,2,3,3,2,3,2,2,1,2,3,1,2,3,1,1,3,1,1,2,3,2,1,1,
		2,3,1,1,2,1,1,2,2,1,3,1,2,3,2,1,2,2,1,1,1,3,2,2,1,2,2,2,1,2,1,3,2,1,3,1,
		3,1,1,3,2,2,3,3,2,1,2,1,3,3,3,2
	]
];

var subjective_question=[
    [
		"Q1. What are the difference between WAG 5 and WAG 7 locomotive bogie?",
		"Q2. How brake power is checked in WAG 5 and WAG 7 locomotive?",
		"Q3. Explain wheel skidding in locomotive and how it can be minimized?",
		"Q4. How load is transmitted in WAG5 locomotive?",
		"Q5. Write the brief description of WAG5 bogie overhauling.",
		"Q6. What are the difference between WAG5 and WAP4 Locomotive Bogie?",
		"Q7. Briefly describe the procedure of Axle box overhauling.",
		"Q8. What are the gauges used by mechanical inspection section during schedule inspection of Loco?",
		"Q9. How will you check the under gear of locomotive during trip inspection?",
		"Q10. What is the procedure for thorough inspection of Axle Box?",
		"Q11. What are the works to be ensured before lifting a WAG5/WAG7 locomotive?",
		"Q12. Write the procedure to change the brake shoes in a locomotive during inspection in shed."
	]
];

var subjective_answer=[
    [
		"<strong>Answer :</strong></p><p>1. In WAG5 cast steel bogie where as in WAG7 fabricated bogie.<br />2. In WAG5 there are one center pivot and two side bearers per bogie where as in WAG7 there are four side bearers. <br />3. In WAG5 suspension bearing and oil pump are there where as in WAG 7 suspension tube with taper roller bearing in ends.<br />4.&nbsp; Equalizer shape and size is different.<br />5. In WAG 5 Bogie there is no compensating beam where as in WAG7 has compensating beam..<br />6. Normally in WAG 5 traction motor is TAO where as in WAG7 traction motor is Hitachi.<br />7. Directions of traction motor fitment are different.<br />8. In WAG5 only helical spring are provided as shock absorber but in WAG7 additionally hydraulic dumpers are provided.<br />9. Brake pull rods are of different design.<br />10. Thrust pad type axle box is used in WAG 7 bogie where as in WAG5 roller bearing type axle box is used. <br />11. Longitudinal and lateral clearance are different in WAG5 and WAG7 locomotive.<br />12.Load distribution are also different.</p>",
		"<p><strong>Answer :</strong></p><p>1. Place the locomotive, whose brake power is to be tested, preferably on a level track, so that locomotive does not roll down when it&rsquo;s brakes are released. Loco wheels and rail should be dry.<br />2.&nbsp; Energies the locomotive and prepare sufficient MR pressure.<br />3.&nbsp; Apply the direct brakes through SA-9.<br />4.&nbsp; Ensure BC pressure 3.5 Kg/cm sq.<br />5.&nbsp; Put the reverser in &lsquo;&lsquo;forward&rsquo;&rsquo; position&nbsp; and blower in ON Mode.<br />6. For WAG-5 take 03 notches in steps notch by notch, locoshould not be moved. Current limit will be 600A. Samemade normal and repeat the procedure for reverser in reverse condition.<br />7.&nbsp; For WAG-7 take 02 notches in steps notch by notch, loco should not be moved. Current limit will be 600A. Same made normal and repeat the procedure for reverser in reverse condition.</p>",
		"<p><strong>Answer :</strong></p><p>During the operation of locomotive when braking force exceeds the limit of adhesion, wheel got skidded. This can be due to either faulty operation of train or defective braking equipment of train. Locomotive braking force could be higher due to incorrect setting of automatic brake valve, independent brake valve and pressure limiting valve or due to malfunctioning of proportionate vale,&nbsp; distributor valve , C2 relay valve and VEF. This can also however happen if the pressure gauges are not calibrated properly. <br />Wheel skidding is also noticed under adverse adhesion conditions caused by oil and grease on the rail table , wet rails and falling of tree leaves and salt on the tracks. Poor brake power of the train can also result into wheel skidding, in certain condition.<br />Application of independent brake or during train braking not using of PVEF by Driver can be the reasons of wheel skidding.<br />To avoid wheel skidding, it is necessary to maintain the brake equipment in perfect working order and setting of equipment to designated value. Locomotive brake should be applied judiciously. In case the poor brake power of train is observed by the driver, he may advise control for joint checking of brake power and for corrective action and ensure pressing of PVEF&nbsp; switch while applying train brakes.</p>",
		"<strong>Answer :</strong></p><p>The weight of the locomotive body is transmitted to the bogie at the pivot and at the two load bearers to form a three point support. The centre pivot carries approximately 60% of vertical load while side bearers share remain 40%.<br />Bogie frame transmit load to the equalizer through long deflection helical springs. Equalizers transmit to the axle box. This force acts over the wheel through journal and ultimately the total load goes to the Rail.</p>",
		"<p><strong>Answer :</strong></p><p>a) All brake hanger lever to disconnect and brake cylinder piston toremove, check any defect of worn-out bushes and pins.<br />b) Bogie frame to clean, remove all dirt and oils from frame, side bearer,and center pivot.<br />c) Bogie frame to be washed by water jet and put into water tankcontaining caustic soda and cleaning agent for 24 to 48 hrs.Cleaning mixture is agitated by forced air for better cleaning.<br />d) Bogie to remove from the tank and washed by water jet.<br />e) Bogie to place on the stand for checking of crack and worn out liners and wear plates.<br />f)&nbsp; If required, square ness of bogie to be ensured with gauge as per standard.<br />g) All worn out defective wear plates and bushes to be changed. Overhauled hanger lever to fit with new bushes, new pins, split cottersand split pins.<br />h) All brake cylinders to overhaul and fit, head disc piston to change and all rubber gasket in pipe line to change. Brake cylinders are tobe tested by external air supply for any air leakages.<br />i)&nbsp; Bogie critical points to be checked by dry penetration test to detectany crack ness.<br />j)&nbsp; After fitment of all accessories final clearances and gaps to be checked.</p>",
		"<p><strong>Answer :</strong><br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />Flexi coil bogie is used in WAP1 to WAP4 locomotive. The difference between &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br />WAG5 and WAP4 bogies are &ndash;</p><p>1) WAG5 bogie is tri-mount CO-CO Bogie having some restriction for speed limit due to lack of flexibility laterally&nbsp;&nbsp; as because it is designed for single stage suspension, so it is suitable for goods service only.</p><p>2) WAP1 to WAP4 locomotives are designed for coaching service. So its speed and flexibility should be better. In view of this flexi coil Bogie has been designed. In this flexible Bogie there are two stage of suspension system. Primary( in between wheel and Bogie) and secondary( between Bogie to Body). This arrangement of secondary suspension is done by providing one Bogie Bolt Star and heavy springs are fitted in main Bogie and Body rest on that bogie bolt star. So body movement flexibility is achieve,both vertically and transversely keeping the main bogie undisturbed.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As bogie bolt star fully floating type so no equalizer is also required. To ensure better damping two numbers frictiondamper between bogie&nbsp; and&nbsp; bogie bolt star are provided.</p>",
		"<p><strong>Answer :</strong></p><p>1. Axle box is released from the wheel set.<br />2. Remove the back ring, press out the roller bearing, distance piece and outer bearing.<br />3. Repair the Shell of Axle box &ndash; Check all liners and change if required. <br />Check the crown by DPT test and clean this.<br />&nbsp;4. Clean the Roller bearing &ndash;<br />a) Remove the grease.<br />b) Clean with oil (Oil bath cleaning)<br />c) Clean by dry air.<br />d) Clean by dry cloth.<br />e) Store it in dry room with proper covering.<br /><strong>Assembling-</strong><br />1. Fit the inside roller bearing into the Shell.<br />2. Fit the distance piece.<br />3. Fit the outer bearing.<br />4. Fit the back ring and tight the back ring bolts.<br />5. Fit the racer and check the radial clearance. It should be0.115 t o .165 mm.<br />6.Fill the axle box with grease (Lithium base) and fit the axle box&nbsp; in the same bearing.<br />7. Fit the collar plate and loose lip and check the free movement of axle box.</p>",
		"<p><strong>Answer :</strong> <br /><strong>TWG-1 (tread wear gauge) &ndash; </strong>check the wear limit of wheel profile as root wear, flange wear &amp; tread wear.<br /><strong>Digital wheel diameter gauge &ndash;</strong>take the diameter of the wheel<br /><strong>Face distance gauge &ndash; </strong>take distance between wheel face in every wheel set.<br /><strong>Filler gauge &ndash; </strong>use to check the longitudinal &amp; lateral clearance.<br /><strong>CBC Go/No Go gauge &ndash; </strong>check the wearing of CBC knuckle<br /><strong>Caliper &amp; steel rule &ndash;</strong>use to check height of rail guard , side bearer etc.</p>",
		"<strong>Answer :</strong><br />During trip inspection check the following &ndash;<br />A. Bogie <br />1. Remove accumulation of paper or other foreign matter the bogie might have picked up on the run.<br />2. Remove as far as possible oil laden and road bed dirt from the exterior surfaces of the bogies.<br />3. Examine visually the bogies to detect loose, defective, crack and missing parts.<br />4. Inspect the wheel for visual defects such as crack, flat spot (skidding) etc.<br />&nbsp;B. Brake gear &ndash;<br />1. Give a general check on the brake rigging for loose nuts, pins, intactness of &lsquo;J&rsquo; clamp, safety sling etc. <br />2. Ensure that the brake shoes gap not less than 10 mm.<br />3. Apply the brake of the locomotive and check that all brake-cylinder piston operating normal and piston travel within limit. <br />4. Check the wear of the brake shoes and replace if necessary.<br />5. Observe any leakage in the bogie body connecting pipe and rectify.</p><p>C. Traction motor and suspension bearings &ndash;</p><p>Check the oil level. Top up if necessary and record in log book the amount of oil added&nbsp; ( if pit is available).</p><p>D. Traction motor gear case &ndash;<br />1. Check the amount of lubricant in the gear case and top up if necessary. <br />2. Check gear case for any damage to felt seal and oil leakage. Rectify/direct to shed if heavy leakage is observed.</p><p>E. Axle Roller Bearings &ndash; <br />Check the temperature of axle box after arrival and check any grease thrown from the axle box.</p><p>F. Suspension springs and equalizer <br />&nbsp;Visual examine all the suspension springs for any crack and damage.</p><p>G. Return current Shunts &ndash;<br />1. Ensure that all the shunt connections between bogie and body are intact.</p><p>H. Sanding and Sand Pipe &ndash;<br />1. Examine the sand delivery pipes for any damage and ensure proper alignment.<br />2. Inspect for any damage and leakage of air pipe.<br />3. Fill the sand boxes with sand of specified quality.<br />4. Check the sand ejectors for proper functioning and see thatsand box covers are intact.</p>",
		"<p><strong>Answer :</strong><br />Axle box is main equipment for free movement of wheel set assembly on which equalizer rest and transfer load to the rail. In thorough inspection we have to cover following checks:<br />Check the temperature of axle box if loco comes from just after service.<br />Check visually any grease leakage.<br />Check liners intactness and condition.</p><p>Check and ensure proper fixation of the axle box cover and color plates.<br />Axle box front covers and color plates to be removed for ultrasonic testing of axle and re new the grease.<br />Send a sample of grease to laboratory for testing.<br />Measure and record longitudinal and lateral clearances between axle box and bogie pedestal liners. Replace liners if the clearances exceed service limits.</p>",
		"<strong>Answer :</strong><br />When bogies are required to be removed from the locomotive, the following preparations are to be taken &ndash;<br />1. Place the locomotive on lifting bay.<br />2. Disconnect all the following before any attempt is made forlifting of the locomotive for running out the bogies.<br />a) Safety lug pins and strap in board transom and U clamps.<br />b) Air brake pipe connections between bogie and body.<br />c) Hand brake chains.<br />d) Sand hose pipe connections.<br />e) Air duct connections.<br />f) Traction motor cable connections.<br />g) Speedo meter connections.<br />h) Return current shunts between bogie and body.<br />i) Readiness of stand for placement of lifted bogie.<br />j) Sling and lifting tackles should be checked for good condition.<br />k) Crane should be tested.<br />l) Ensure no man is working and wedge under wheel.</p>",
		"<p><strong>Answer :</strong> <br />During schedule inspection of locomotive replacing of worn out brake shoes is an important regular activity. For replacement of brake shoes in a proper and safe way following procedure is adopted.&nbsp;&nbsp; <br />Place the loco in pit line and apply wheel wedge properly. Place a board written &lsquo;Men At Work&rsquo;.<br />Workers must be equipped with safety shoes, helmet and hand gloves.<br />Isolate&nbsp; bogie&nbsp; cut out cock/drain the pressure.<br />Collect the new brake shoes and place near the wheel.<br />Open the all lower pull rod pin and make the gap.<br />Open brake shoes cutter and remove worn out shoes.<br />Fit the new brake shoes with brake shoes cutter properly.<br />Fit the all pull rod pin and secured properly.<br />Adjust the clearance between brake shoes wheel 10mm (in release position) with slack adjuster &amp; pull road.<br />Apply pneumatic pressure and check operation&nbsp; and&nbsp; measure the piston stroke in apply condition(95-105mm).</p><p><strong>&nbsp;Note: </strong><br />During fitment of brake shoes holder tightness in parallel to wheel tread&nbsp;&nbsp; to be ensured and touching of brake shoes with flange to be avoided.</p>"
	]
];