var objective_topic=["Pneumatic : Objective Question"];
var subjective_topic=["Pneumatic : Subjective Question"];

var objective_question=[
    [
		"1: How many non-return valves in RS pressure circuit",
		"2: Setting of safety valve of RS pressure circuit",
		"3: Lubricant oil capacity of baby compressor is",
		"4: Capacity of RS reservoir is",
		"5: No. of needles in RS pressure gauge is",
		"6: When Baby Compressor is off, RS pressure is maintained by",
		"7: Source of RS pressure is",
		"8: RS pressure reaches to pantograph via",
		"9: Source of MR pressure is",
		"10: Air delivery capacity of CP TRC 1000 is",
		"11: No. of low pressure valve in a compressor TRC1000 is",
		"12: No. of high pressure valve in a compressor TRC1000 is",
		"13: Setting of safety valve of CP inter cooler is",
		"14: Lubricating capacity of CP TRC1000 crank case is",
		"15: Capacity of oil batch filter or CP TRC 1000 is",
		"16: Type of coupling between compressor and motor",
		"17: MR pressure is controlled within a range by",
		"18: Size of control reservoir in comparison to Main Reservoir",
		"19: Location of control reservoir in WAG5 loco is in",
		"20: CP is ________ type compressor.",
		"21: Minimum pressure required to reach the MR pressure to MR ",
		"22: RGCP setting in WAG7 loco is",
		"23: Name of additional needle in MR gauge in WAG5",
		"24: Auto drain valve is provided with",
		"25: No. of centrifugal oil separator in WAG5 loco is",
		"26: Location of air control COC in WAG5 is near",
		"27: Duplex check valve is tapped from MR reservoir no.",
		"28: Non return valve is provided between following main reservoir",
		"29: Incoming pr. of A9, SA9 is tapped after MR reservoir no.",
		"30: Incoming pr. of C2 relay valve for BP charging is taken from MR ",
		"31: Coupler of compressor greasing is done using",
		"32: Capacity of TRC 2000 compressor is",
		"33: Capacity of lubricant oil is TRC2000 CP is",
		"34: Color of MR equalizing pipe cock is",
		"35: Trade name of CP oil is",
		"36: Name of independent air brake valve is",
		"37: what is the Direction of rotation of main compressor viewed from non-driving end?",
		"38: Incoming MR pressure is tapped for BC C2W from MR reservoir number",
		"39: Brake cylinder pressure is applied up to",
		"40: Permissible BC leakage is",
		"41: No. of pipe connection to A9",
		"42: No. of pipe connection to SA9",
		"43: No. of foundation bolt for SA9 is",
		"44: BC equalizing pipe angle cock colour is",
		"45: For application of independent air brake following port of MU2B is responsible",
		"46: Fixation bolt of MU2B valve is",
		"47: Double check valve A21 is located in WAG5 loco is",
		"48: Pressure cut off switch in BC circuit is",
		"49: Position of A9 is",
		"50: Minimum schedule in which SA9 is inspected",
		"51: BP pipe pressure is controlled by the valve",
		"52: BP pressure in WAG5/WAG7 loco is",
		"53: Source of BP pressure is",
		"54: Incoming pressure of C2 relay of BP pr. is taken from",
		"55: Dimension of BP charging COC is",
		"56: Colour of BP angle cock is",
		"57: Position of SA9 valve is",
		"58: Foundation bolt of A9 is",
		"59: No. of base bolt for A9 is",
		"60: No. of pipe line connected with A9 base is",
		"61: BP leakage permissible is",
		"62: If BP pr. is dropped proportionate brake is applied through",
		"63: No. of pipe line connection in C3W distribution valve is",
		"64: To isolate C3W D valve its cock handle to keep",
		"65: To remove C3W D valve, no. of bolts to removed are",
		"66: C3WD valve is Over Hauled in the inspection schedule",
		"67: For quick application of proportionate brake F/T cock of C3WD ",
		"68: BP pr. should show in BP gauge in full service position of A9 is",
		"69: Train brake application is related with following pressure of loco",
		"70: MV4 valve is provided in the following circuit",
		"71: Air flow measuring valve is related with",
		"72: Air flow measuring valve works in collaboration with",
		"73: No. of port connected in MU2B valve during BP charging/discharging ",
		"74: Setting of BP pressure is",
		"75: In case emergency brake apply by RS, BC gauge will show -",
		"76: By A-9 handle brake can be apply -",
		"77: Feed pipe pressure is required for",
		"78: Feed pipe pr. is",
		"79: Type of feed valve is",
		"80: How many Numberof  MR provided in WAP4 loco ?",
		"81: Incase of loco parting rear loco brake is ensured by",
		"82: MR safety valve provided between -",
		"83: Location of RGEB in WAG5 loco is",
		"84: Colour of feed pipe angle cock is",
		"85: Foundation bolt of C2 relay is",
		"86: Small reservoir connected with C2 relay valve control pipe is called",
		"87: Air dryer provided between -",
		"88: Pipe line connected with Assistant driver Emergency brake valve is",
		"89: Colour of needle of A/F gauge is",
		"90: R6 is having relation with",
		"91: If BP is not charging following is cause for that",
		"92: Position of MU2B in master loco is -",
		"93: Position of MU2B in slave loco is -",
		"94: What type horn is used in locomotive? ",
		"95: Twin tower Air Dryer in WAG7 is provided in between ",
		"96: Panel mounted pneumatic equipment is not provided with",
		"97: Following valve is having two input and one output pipe line",
		"98: Following is not pneumatic pressure control switch",
		"99: Following is not the equipment of ACP circuit",
		"100: VEUL gets energise when -",
		"101: Auto drain valves are fitted in - ",
		"102: MR safety valve is provided between - ",
		"103: Air flow indicator is actuated by - ",
		"104: During ACP in coaching train, AFL works by the action of - ",
		"105: P1 is provided between - ",
		"106: P2 is provided between-",
		"107: RGEB-2 is controlled by - ",
		"108: Setting of RGEB-2 is - "
	]
];

var objectiveoptions=[
    [
		["a) 3 ","b) 4 ","c) 2 "],
		["a) 8 kg/cm2 ","b) 8.2 kg/cm2 ","c) 9.5 kg/cm2 "],
		["a) 850 ml ","b) 650ml ","c) 250ml "],
		["a) 100L ","b) 120L ","c) more "],
		["a) 1 ","b) 2 ","c) none "],
		["a) BC Pressure ","b) MR Pressure ","c) BP pressure "],
		["a) CPA ","b) CP ","c) RGCP "],
		["a) DJ oil separator ","b) HOM ","c) None "],
		["a) CPA ","b) CP ","c) RGCP "],
		["a) 1000L/m ","b) 2000L/m ","c) 500L/m "],
		["a) 2 ","b) 3 ","c) 6 "],
		["a) 2 ","b) 3 ","c) 1 "],
		["a) 12.05 kg/cm2 ","b) 11.5 kg/cm2 ","c) 10.5 kg/cm2 "],
		["a) 11L ","b) 1L ","c) 1.1L "],
		["a) 700ml total ","b) 700 ml each ","c) 1100 ml total "],
		["a) Gear type ","b) bibby type ","c) none "],
		["a) Safety valve ","b) Governor ","c)Transducer "],
		["a) Larger ","b) Smaller ","c) Equal "],
		["a) CAb-1 ","b) Under slung of body ","c) Cab-2 bottom "],
		["a) Two stage rotating ","b)Single stage reciprocating ","c) Two stage reciprocating "],
		["a) 3 kg/cm2 ","b) 10 kg/cm2 ","c) 5 kg/cm2 "],
		["a) 9 -11 kg/cm2 ","b) 8.5 - 10.0 kg/cm2 ","c) 7.0 to 8.0 kg/cm2 "],
		["a) Air flow ","b) Feed pipe ","c) RS pr. "],
		["a) MR1 and 2 ","b) MR 3and 4 ","c) MR 1and 4 "],
		["a) 3 ","b) 2 ","c) 4 "],
		["a) Baby compressor ","b) Near wheel 4 ","c) Near wheel 10 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) MR 1and 2 ","b) MR 3 and 4 ","c) None "],
		["a) 1 ","b) 4 ","c) 3 "],
		["a) 3 ","b) 2 ","c) 4 "],
		["a) Servo gem ","b) SP150 ","c) LL-3 "],
		["a) 2000L/m ","b) 1750L/m ","c) 1000L/m "],
		["a) 1.1 L ","b) 8 L ","c) 12L "],
		["a) Black ","b) Blue ","c) Red "],
		["a) SP 150 ","b) SL100 ","c) T-78 "],
		["a) A9 ","b) SA9 ","c) C2W "],
		["a) clock-wise ","b) Anti-clockwise ","c) None of this as reciprocating type "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 5 kg/cm2 ","b) 3.5 kg/cm2 ","c) 2.5 kg/cm2 "],
		["a) 0.1 kg/cm2/m ","b) 0.2kg/cm2/m ","c) 0.7 kg/cm2/m "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) Red ","b) White ","c) Green "],
		["a) 3-13 ","b) 53-63 ","c) 2-20 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) Cab-1 D/side locker ","b) Cab-1 centre locker ","c) Under frame "],
		["a) RGCP ","b) QWC ","c) SWC "],
		["a) 2 ","b) 3 ","c) 5 "],
		["a) AOH ","b) IC ","c) IA "],
		["a) SA9 ","b) A9 ","c) C2 relay "],
		["a) 3.5 kg/cm2 ","b) 2.5 kg/cm2 ","c) 5 kg/cm2 "],
		["a) RS Pressure ","b) BC Pressure ","c) MR Pressure "],
		["a) MR4 ","b) MR3 ","c) MR1 "],
		["a) 1” ","b) 1 ¼” ","c) ¾” "],
		["a) Green ","b) Red ","c) White "],
		["a) 4 ","b) 5 ","c) 2 "],
		["a) 2 ","b) 4 ","c) 3 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) 0.2 kg/cm2/m ","b) 0.7 kg/cm2/5m ","c) 0.7 kg/cm2/m "],
		["a) C2W relay valve for BP ","b) C3W D valve ","c) SA9 "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) Towards valve ","b) Towards chamber ","c) Middle "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) IA ","b) IC ","c) AOH "],
		["a) Towards valve ","b) Towards chamber ","c) Middle "],
		["a) 2.5 kg/cm2 ","b) 4.5 kg/cm2 approx. ","c) 3.5 kg/cm2 "],
		["a) BC pr. ","b) BP pr. ","c) FP pr. "],
		["a) MR circuit ","b) BP circuit ","c) RS circuit "],
		["a) BP pr. ","b) BC pr. ","c) MR pr. "],
		["a) R6 relay valve ","b) C2 relay valve ","c) none "],
		["a) 2-20 ","b) 53-63 ","c) 3-13 "],
		["a) 3.5 kg/cm2 ","b) 2.5 kg/cm2 ","c) 5 kg/cm2 "],
		["a) 1 kg/ cm²"," b) 1.8 kg/ cm² ","c) 2.5 kg/ cm² "],
		["a) Only loco brake"," b) Only train brake ","c) Both brakes "],
		["a) Quick application of train brake ","b) Quick release for train brake ","c) none "],
		["a) 5 kg/cm2 ","b) 6 kg/cm2 ","c) 3.5 kg/cm2 "],
		["a) D1 ","b) D24B ","c) VAIB "],
		["a) 4"," b) 5 ","c) 6 "],
		["a) C2W relay valve ","b) F1 selector valve ","c) A9 "],
		["a) MR1–MR2 ","b) MR-2–MR3 ","c) MR3–MR4 "],
		["a) Cab -1 Driver side locker ","b) Cab-1 centre locker ","c) Corridor cab1 "],
		["a) Red ","b) Green ","c) White "],
		["a) 2 ","b) 3 ","c) 4 "],
		["a) Auxiliary reservoir ","b) Volume reservoir ","c) Additional chamber "],
		["a) MR1–MR2 "," b) MR-2–MR3 ","c) MR3–MR4 "],
		["a) BP ","b) FP ","c) MR "],
		["a) Blue – blue ","b) Red – white ","c) Green – red "],
		["a) RGCP ","b) RGEB ","c) RGAF "],
		["a) MU2B in lead ","b) Rear cab A9 I/C cock open ","c) Leading cab A9 I/C cock closed "],
		["a) Trail"," b) Lead","c) Closed"],
		["a) Lead"," b) Trail ","c) Closed "],
		["a) Pneuphonic Horn. ","b) Electric horn. ","c) Both a and b "],
		["a) MR 1 and 2 ","b) MR 2 & 3 ","c) MR 3 & 4 "],
		["a) WAG7 ","b) WAG9 ","c) WAG5 "],
		["a) Duplex check valve ","b) Double check valve ","c)C3wD valve "],
		["a) P1 ","b) RGEB ","c) QPH "],
		["a) P1 ","b) P2 ","c) SWC "],
		["a) MCP starts ","b) MCP stop ","c) MCP working "],
		["a) MR1 & MR2"," b) MR2 & MR3 ","c) MQ3 & MR4 "],
		["a) MR2 & MR3","b) MR3 & MR4 ","c) MR1 & MR4 "],
		["a) RGAF"," b) R6 ","c) AFMV "],
		["a) RGEB2 & PR2 ","b) RGAF & PR2 ","c) P2 & PR2 "],
		["a) A9 inlet pipe & MU2B ","b) A9 out let cock & MU2B ","c) MU2B & GR "],
		["a) MU2B & L/T cock ","b) L/T cock&BP angle cock ","c) None of this "],
		["a) BP pressure ","b) MR pressure ","c) BC pressure "],
		["a) 4.2 Kg/ 3 kg"," b) 1.5 kg/3 kg ","c) 5 kg/3.5 kg"]
	]
];

var objectiveAnswer=[
    [
		1,1,3,1,2,2,1,2,2,1,1,3,2,3,1,2,2,2,2,3,3,2,2,1,2,2,2,2,2,1,1,1,2,3,1,2,
		2,3,2,1,2,1,3,3,3,2,1,3,3,2,2,3,3,2,1,1,3,2,1,2,2,2,2,2,3,3,1,3,2,2,1,1,
		3,3,2,3,2,2,2,3,2,2,1,3,3,2,2,1,2,3,3,2,2,1,2,3,2,3,3,2,1,1,2,2,2,2,1,1
	]
];

var subjective_question=[
    [
		"Q1. Write the short note on main Compressor of locomotive.",
		"Q2. What are the parts of main compressor of locomotive?",
		"Q3. What safety precautions are to be taken during handling pneumatic equipments?",
		"Q4. How IAB is applied in WAG7 locomotive?",
		"Q5. How BP is charged in WAG7 loco?",
		"Q6. Write about the Storage procedure of rubber items.",
		"Q7. Give brief description of C3W distributor valve?",
		"Q8. WHY IS AN AIR DRYER IMPORTANT?",
		"Q9. WHAT DOES AN AIR DRYER DO?"
	]
];

var subjective_answer=[
    [
		"<p>The ElGI air compressor model TRC 1000 MN is a three cylinder, two stage,<br/>reciprocating, air cooled and splash lubricated compressor driven by an electric<br/>motor through a bibby coupling.</p><p>&nbsp;It consists of three cylinders arranged in a &lsquo;W&rsquo; form on a crank case. Oil bath air filters are fitted to the suction side of the LP cylinder heads. <br/>The discharge ports of the LP cylinder heads are connected to the radiator called inter cooler for effective cooling.</p><p>&nbsp;Inter cooler is connected to the suction port of the HP cylinder head. The discharge port of the HP cylinder head is fitted with a box type after cooler. The compressed air flows from delivery of LP cylinder through inter cooler to HP cylinder and delivered after cooling in after cooler.</p><p>&nbsp;The compressor is coupled with a motor and mounted on a rigid, compact base. The air filter and other pipe fittings are all clamped properly to arrest vibration. A fan with a fan guard is provided to direct cool air on to the compressor unit. The fan draws the air over the motor there-by cooling the motor also. An eye bolt used to lift motor is provided at the terminal belt side of the motor. </p>",
		"<p>Crank Case, Cylinder and Cylinder Head, Connecting Rod crank Saft Assembly, piston and<br/>piston Rings, Disc valves, inter Cooler, Safety Valve and After Cooler, Flexible resilient<br/>Coupling (Bibby coupling)</p>",
		"<p><strong>Answer :</strong></p><p>During handling pneumatic equipment &ndash; </p><p>The user must familiarize himself with the basic safety precautions, neglect of which can lead to serious injury including fatal one.</p><p>The air brake system operates at high pressure. Ensure that the system or relevant system of the system are duly isolated and drained of all residue pressure before removing the valve or port thereof.</p><p>Some brake valves or their sub-assemblies include spring in pre- compressed condition. Precaution should be taken by using proper fixtures and or following appropriate method of dismantling as recommended against each valve, so that the springs and their allied parts do not fly and cause personal injury.</p>",
		"<p>&nbsp;IAB is applied for only locomotive braking. It is controlled by the operation of SA-9 independent brake valve, provided at both cabs. It has two positions Release and Application. MR air pressure from main reservorNo.4 is piped to port no 30of SA-9 via isolating valve.<br/>MR air pressure from MR No.4 is also piped to port no 1 of C2 relay valve.<br/>When SA9 handle is moved on application position ,maximum 3.5 Kg/cm2 will flow to control port of C2 relay via ports 2 and 20 of MU-2B ( Which is kept in lead position) and Double check valve. Now C2&nbsp; relay valve port is opened and MR-4 pressure goes to Brake cylinder through Isolating Cock and flexible hose pipe. The brake pressure shows in the BC gauges.</p>",
		"<p><strong>Answer :</strong><br/>With the control of BP pressure control the automatic brake application in train. Control valve(A9) is connected with MR-4 air pressure. As A-9 valve is kept in release position, A-9 pressure limiting valve converts MR pressure into BP actuating (control) pressure&nbsp; of 5Kg/cm sq. as it is preset.&nbsp; Actuating BP pressure goes to BP C2W relay through MU2B in lead. C2W connected with MR-3 air pressure. As C2W relay is actuated, C2W allow to go same pressure of air to BP line from MR-3 pressure. When kept A-9 in apply condition BP pressure and actuating pressure is released from the exhaust of A-9. There is an air flow measuring valve to show the flow of air in BP line. The A9 has five positions Release, Minimum reduction, Full service, over reduction and Emergency. </p>",
		"<p>As so many rubber items are used in pneumatic valves so storage procedure of<br/>rubber items is very important.<br/>Rubber components should be kept away from direct sun light preferably in dark<br/>place. Direct sunlight causes much faster degradation of the rubber components.<br/>They should be stored in a cool place as far as practicable, preferably below 30deg C.<br/>The humidity of the storage condition should not be such that condensation ofmoisture takes place on the surface of the material.<br/>In the nearer of these materials, any loose electrical connections should be avoided,<br/>as these cause production of ozone which adversely affects rubber.<br/>Rubber materials should be stored away from contact with certain materialsparticularly those containing copper and manganese which act as poisoning agents,<br/>aiding their fast degradation. </p><p>Under no circumstances rubber materials should be stressed during storage. The<br/>portions under stress undergo deformations with permanent set leading to<br/>degradation. The materials should be stacked in such a way so that any superimposedstresses are substantially avoided.<br/>Any contact with grease or oil should be avoided as these cause swelling, softening<br/>and deterioration of rubber materials.<br/>French chalk should liberally be applied on the surface of rubber materials. </p>",
		"<p><strong>Answer :</strong><br/>The C3W distributor valve with passenger/ goods change over cock, support reservoir, isolating cock and filter is used in locomotive brake system for operation of graduated release automatic braking in the locomotive. <br/>This is a mechanical valve, which causes application of loco brake in proportion to the reduction of BP pressure. It has got three connections &ndash; one with the BP pipe line, another with MR pipe line and other with the outlet connected to mechanical VEF through reducing valve for VEF.<br/>This valve is provided with an isolating handle, which can be operated manually to keep the C3W distributor valve in service. In service position the isolating handle should be towards valve side. To isolate the valve the handle is required to be operated towards reservoir side. After isolating the valve it is required to be released the pressure from the release valve which is provided at the bottom of this valve. To release the valve the releasing handles to be pulled.<br/>This valve also is having a freight / passenger change over cock. When working goods train the cock should be towards reservoir side while working coaching train the cock should towards valve side to reduce the brake application time. </p>",
		"<strong>Answer- </strong><br/>Moisture in a compressed air system can&hellip;<br/>1. Corrode air lines and equipment<br/>2. Wash away equipment lubrication<br/>3. Decrease reservoir volumes<br/>4. Moisture and oil may disturb specified timing of the air brake valves<br/>5. Moisture and oil also cause damage to rubber components of air brake valves and other equipment.<br/>All these&nbsp; problems can be avoided by using air dryer. </p>",
		"<strong>Answer - </strong><br/>Air drier does the following functions- <br/>1. Removes oil droplets from air<br/>2. Removes dirt particles from air<br/>3. Removes moisture from air</p>"
	]
];